import { randomUUID } from "node:crypto";
import { describe, expect, it } from "vitest";
import { executePremiumBusinessAction, recordPremiumBusinessAiCompletion, validatePremiumBusinessAiCompletion, type PremiumBusinessAuthorization } from "../src/server/premium-business-store-engine";
import { MemorySuiteStore } from "../src/server/suite-store";
import type { PremiumActionIdFor, PremiumModuleId } from "../src/shared/premium-business-actions";

const clock = "2026-08-24T18:00:00.000Z";
const deps = { now: () => new Date(clock) };

async function fixture(plan: "scale" | "fleet" = "fleet", modules: PremiumModuleId[] = ["projects", "drive", "channels", "operations", "assistant"]) {
  const store = new MemorySuiteStore(plan); const userId = randomUUID(); const workspace = await store.getOrCreateWorkspace(userId);
  for (const moduleId of modules) await store.enableModule(userId, moduleId);
  const auth: PremiumBusinessAuthorization = { userId, workspaceId: workspace.id, role: "owner", scopes: ["*"] };
  const run = <M extends PremiumModuleId>(moduleId: M, actionId: PremiumActionIdFor<M>, input: Record<string, unknown>) => store.runInWorkspaceTransaction(userId, () => executePremiumBusinessAction(store, auth, moduleId, actionId, input, deps));
  return { store, userId, auth, run };
}

function approve(userId: string) { return { approved: true, approvedBy: userId, approvedAt: clock, reason: "Reviewed exact content and evidence" }; }
function first<T extends { records: Array<unknown> }>(result: T) { const record = result.records[0]; if (!record) throw new Error("Expected a record."); return record as Awaited<ReturnType<MemorySuiteStore["getRecord"]>> & {}; }

describe("premium SuiteStore production adapter", () => {
  it("persists one atomic receipt and one result across concurrent identical retries", async () => {
    const { store, userId, auth } = await fixture("scale", ["projects"]); const input = { key: "atomic", name: "Atomic", outcome: "One durable project", idempotencyKey: "premium-atomic-project-0001" };
    const [created, replayed] = await Promise.all([
      store.runInWorkspaceTransaction(userId, () => executePremiumBusinessAction(store, auth, "projects", "project-create", input, deps)),
      store.runInWorkspaceTransaction(userId, () => executePremiumBusinessAction(store, auth, "projects", "project-create", input, deps)),
    ]);
    expect(created.kind).toBe("command"); expect(replayed.audit.replayed).toBe(true); expect(first(created).id).toBe(first(replayed).id);
    expect(await store.listRecords(userId, { moduleId: "projects", recordType: "project", limit: 20 })).toHaveLength(1);
    expect(await store.listRecords(userId, { moduleId: "projects", recordType: "premium-command-receipt", limit: 20 })).toHaveLength(1);
    await expect(store.runInWorkspaceTransaction(userId, () => executePremiumBusinessAction(store, auth, "projects", "project-create", { ...input, name: "Changed" }, deps))).rejects.toThrow(/different input/);
  });

  it("enforces authoritative plan, role, scope, and workspace boundaries before persistence", async () => {
    const scale = await fixture("scale", ["projects"]); await expect(scale.store.runInWorkspaceTransaction(scale.userId, () => executePremiumBusinessAction(scale.store, scale.auth, "operations", "party-create", { name: "Denied", kind: "customer", currency: "USD", idempotencyKey: "premium-denied-party-001" }, deps))).rejects.toThrow(/\$200\/month fleet plan/);
    const other = await fixture("scale", ["projects"]); const project = first(await scale.run("projects", "project-create", { key: "private", name: "Private", outcome: "Tenant only", idempotencyKey: "premium-private-project1" }));
    await expect(other.run("projects", "issue-create", { projectId: project.id, title: "Cross tenant", priority: "high", points: 2, idempotencyKey: "premium-cross-tenant-01" })).rejects.toThrow(/not found in this workspace/);
    const scopedAuth = { ...scale.auth, scopes: ["projects:read"] }; await expect(scale.store.runInWorkspaceTransaction(scale.userId, () => executePremiumBusinessAction(scale.store, scopedAuth, "projects", "issue-create", { projectId: project.id, title: "No scope", priority: "low", points: 1, idempotencyKey: "premium-no-scope-issue1" }, deps))).rejects.toThrow(/projects:write scope/);
    expect(await other.store.getRecord(other.userId, project.id)).toBeUndefined();
  });

  it("executes all eight planning actions with durable versions, capacity, approval, and AI audit", async () => {
    const { store, userId, auth, run } = await fixture("scale", ["projects"]); const project = first(await run("projects", "project-create", { key: "northstar", name: "Northstar", outcome: "Deliver safely", idempotencyKey: "premium-project-create01" }));
    const foundation = first(await run("projects", "issue-create", { projectId: project.id, title: "Foundation", priority: "high", points: 3, idempotencyKey: "premium-issue-foundation" })); const release = first(await run("projects", "issue-create", { projectId: project.id, title: "Release", priority: "normal", points: 5, idempotencyKey: "premium-issue-release001" }));
    const linked = first(await run("projects", "dependency-link", { issueId: release.id, dependsOnIssueId: foundation.id, expectedVersion: 1, idempotencyKey: "premium-dependency-link1" })); expect(linked.data.version).toBe(2);
    const ready = first(await run("projects", "issue-transition", { issueId: foundation.id, toState: "ready", expectedVersion: 1, reason: "Evidence complete", idempotencyKey: "premium-issue-transition" })); expect(ready.state).toBe("ready");
    const cycleResult = await run("projects", "cycle-draft", { projectId: project.id, title: "Cycle one", capacityPoints: 8, issueIds: [foundation.id, release.id], idempotencyKey: "premium-cycle-draft-001" }); const cycle = first(cycleResult);
    const committed = first(await run("projects", "cycle-commit", { cycleId: cycle.id, contentHash: cycle.data.contentHash, approval: approve(userId), dryRun: false, idempotencyKey: "premium-cycle-commit-01" })); expect(committed.state).toBe("active");
    const plan = await run("projects", "plan-propose", { projectId: project.id, objective: "Propose the next bounded cycle", evidenceIds: [project.id, foundation.id], promptVersion: "northstar-plan-v1", modelId: "local/grounded", approval: approve(userId), dryRun: false, idempotencyKey: "premium-plan-propose-01" }); expect(plan).toMatchObject({ kind: "ai-action", records: [{ recordType: "premium-ai-request-audit", data: { output: null, confidence: null, fabricatedOutputAllowed: false } }] });
    const health = await run("projects", "health-explain", { projectId: project.id, question: "What is blocked?", evidenceIds: [project.id, linked.id], promptVersion: "northstar-health-v1", modelId: "local/grounded", dryRun: true, idempotencyKey: "premium-health-dry-run1" }); expect(health).toMatchObject({ kind: "command", records: [], preview: { modelInvoked: false, output: null } });
    expect(await store.listRecords(userId, { moduleId: "projects", recordType: "premium-command-receipt", limit: 100 })).toHaveLength(9);
  });

  it("executes all eight private-file actions and leaves private share material out of durable receipts", async () => {
    const { store, userId, run } = await fixture("scale", ["drive"]); const approval = approve(userId); const vault = first(await run("drive", "vault-create", { name: "Contracts", classification: "restricted", idempotencyKey: "premium-vault-create-001" }));
    const registered = await run("drive", "file-register", { vaultId: vault.id, name: "agreement.pdf", objectKey: "tenant/contracts/agreement-v1", contentType: "application/pdf", sizeBytes: 2048, checksum: "a".repeat(64), approval, dryRun: false, idempotencyKey: "premium-file-register-01" }); const file = registered.records.find((record) => record.recordType === "file")!;
    const versioned = await run("drive", "file-version-add", { fileId: file.id, objectKey: "tenant/contracts/agreement-v2", sizeBytes: 4096, checksum: "b".repeat(64), expectedVersion: 1, approval, dryRun: false, idempotencyKey: "premium-file-version-001" }); const current = versioned.records.find((record) => record.recordType === "file")!;
    const sharePlan = await run("drive", "share-preview", { fileId: file.id, expiresAt: "2026-08-25T18:00:00.000Z", permission: "view" }); const share = await run("drive", "share-create", { fileId: file.id, expiresAt: "2026-08-25T18:00:00.000Z", permission: "view", previewHash: sharePlan.preview!.previewHash, approval, dryRun: false, idempotencyKey: "premium-share-create-001" }); expect(share.privateOutput?.shareToken).toMatch(/^[0-9a-f-]{36}$/);
    const analysis = await run("drive", "document-understand", { fileId: file.id, question: "Which facts are supported?", evidenceIds: [file.id], promptVersion: "harbor-understand-v1", modelId: "local/grounded", approval, dryRun: false, idempotencyKey: "premium-document-ai-001" }); expect(analysis.aiAction).toBeDefined();
    const retained = first(await run("drive", "retention-set", { fileId: file.id, retainUntil: "2026-08-23T18:00:00.000Z", legalHold: false, expectedVersion: Number(current.data.version), approval, dryRun: false, idempotencyKey: "premium-retention-set-01" }));
    const deleted = first(await run("drive", "file-delete", { fileId: file.id, expectedVersion: Number(retained.data.version), reason: "Owner-approved removal", approval, dryRun: false, idempotencyKey: "premium-file-delete-0001" })); expect(deleted.state).toBe("deleted");
    const receipts = await store.listRecords(userId, { moduleId: "drive", recordType: "premium-command-receipt", limit: 100 }); expect(JSON.stringify(receipts)).not.toContain(String(share.privateOutput?.shareToken)); expect(receipts).toHaveLength(7);
  });

  it("executes all eight topic-first communication actions and never silently sends AI text", async () => {
    const { store, userId, run } = await fixture("scale", ["channels"]); const approval = approve(userId); const stream = first(await run("channels", "stream-create", { key: "launch", name: "Launch", purpose: "Coordinate release", idempotencyKey: "premium-stream-create-01" })); const topic = first(await run("channels", "topic-create", { streamId: stream.id, title: "Release date", intent: "Choose the date", idempotencyKey: "premium-topic-create-001" }));
    const preview = await run("channels", "message-preview", { topicId: topic.id, body: "Tuesday is the proposed date." }); const posted = first(await run("channels", "message-post", { topicId: topic.id, body: "Tuesday is the proposed date.", previewHash: preview.preview!.previewHash, approval, dryRun: false, idempotencyKey: "premium-message-post-001" }));
    const summary = await run("channels", "topic-summarize", { topicId: topic.id, question: "What date was proposed?", evidenceIds: [posted.id], promptVersion: "threadline-summary-v1", modelId: "local/grounded", approval, dryRun: false, idempotencyKey: "premium-topic-summary-01" }); expect(summary.records[0].data).toMatchObject({ output: null, automaticMutationAllowed: false });
    const digest = await run("channels", "digest-draft", { streamId: stream.id, instruction: "Draft a cited digest", evidenceIds: [topic.id], promptVersion: "threadline-digest-v1", modelId: "local/grounded", approval, dryRun: false, idempotencyKey: "premium-digest-draft-01" }); expect(digest.records[0].data).toMatchObject({ automaticSendAllowed: false, output: null });
    const redacted = first(await run("channels", "message-redact", { messageId: posted.id, expectedVersion: 1, reason: "Approved privacy request", approval, dryRun: false, idempotencyKey: "premium-message-redact1" })); expect(redacted).toMatchObject({ state: "redacted", data: { body: null } });
    const resolved = first(await run("channels", "topic-resolve", { topicId: topic.id, decision: "Ship Tuesday", expectedVersion: 1, idempotencyKey: "premium-topic-resolve-01" })); expect(resolved.state).toBe("resolved");
    expect(await store.listRecords(userId, { moduleId: "channels", recordType: "premium-command-receipt", limit: 100 })).toHaveLength(7);
  });

  it("executes all nine ERP actions with exact integer balance and approval gates", async () => {
    const { store, userId, run } = await fixture("fleet", ["operations"]); const approval = approve(userId); const party = first(await run("operations", "party-create", { name: "Acme", kind: "customer", currency: "USD", idempotencyKey: "premium-party-create-001" })); const item = first(await run("operations", "item-create", { sku: "CONSULT", name: "Consulting", currency: "USD", unitPriceMinor: 25000, idempotencyKey: "premium-item-create-0001" }));
    const order = first(await run("operations", "order-create", { partyId: party.id, currency: "USD", lines: [{ itemId: item.id, quantity: 2 }], idempotencyKey: "premium-order-create-001" })); const invoiceDraft = first(await run("operations", "invoice-draft", { orderId: order.id, issueAt: clock, dueAt: "2026-09-24T18:00:00.000Z", idempotencyKey: "premium-invoice-draft-01" })); const invoice = first(await run("operations", "invoice-issue", { invoiceId: invoiceDraft.id, contentHash: invoiceDraft.data.contentHash, approval, dryRun: false, idempotencyKey: "premium-invoice-issue-01" }));
    await expect(run("operations", "journal-preview", { currency: "USD", period: "2026-08", memo: "Broken", entries: [{ account: "cash", debitMinor: 50000, creditMinor: 0 }, { account: "revenue", debitMinor: 0, creditMinor: 49999 }] })).rejects.toThrow(/balance exactly/);
    const journalInput = { currency: "USD", period: "2026-08", memo: "Revenue", entries: [{ account: "cash", debitMinor: 50000, creditMinor: 0 }, { account: "revenue", debitMinor: 0, creditMinor: 50000 }] }; const journalPreview = await run("operations", "journal-preview", journalInput); const journal = first(await run("operations", "journal-post", { ...journalInput, previewHash: journalPreview.preview!.previewHash, approval, dryRun: false, idempotencyKey: "premium-journal-post-001" })); expect(journal.data).toMatchObject({ debitMinor: 50000, creditMinor: 50000, immutable: true });
    const payment = await run("operations", "payment-record", { invoiceId: invoice.id, amountMinor: 50000, currency: "USD", reference: "bank-001", approval, dryRun: false, idempotencyKey: "premium-payment-record-01" }); expect(payment.records.find((record) => record.recordType === "invoice")?.state).toBe("paid");
    const variance = await run("operations", "variance-explain", { question: "Explain the invoice total", evidenceIds: [order.id, journal.id], promptVersion: "ledgerline-variance-v1", modelId: "local/grounded", approval, dryRun: false, idempotencyKey: "premium-variance-ai-001" }); expect(variance.records[0].data).toMatchObject({ output: null, mayPostAccountingFacts: false });
    expect(await store.listRecords(userId, { moduleId: "operations", recordType: "premium-command-receipt", limit: 100 })).toHaveLength(8);
  });

  it("executes all nine AI-workbench actions and binds reviewed output to the exact completed model result", async () => {
    const { store, userId, auth, run } = await fixture("fleet", ["projects", "assistant"]); const approval = approve(userId); const source = first(await run("projects", "project-create", { key: "evidence", name: "Evidence", outcome: "Ground claims", idempotencyKey: "premium-evidence-project1" })); const collection = first(await run("assistant", "collection-create", { name: "Evidence set", purpose: "Ground one run", idempotencyKey: "premium-collection-create" }));
    await run("assistant", "source-attach", { collectionId: collection.id, recordId: source.id, citationLabel: "Project outcome", contentHash: "c".repeat(64), idempotencyKey: "premium-source-attach-01" }); const prompt = first(await run("assistant", "prompt-version-create", { name: "Grounded", systemInstruction: "Use only selected evidence.", inputContract: { goal: "string" }, outputContract: { summary: "string", claims: "cited[]" }, idempotencyKey: "premium-prompt-version-01" }));
    const runInput = { promptVersionId: prompt.id, collectionId: collection.id, evidenceIds: [source.id], modelId: "local/audited", goal: "Explain the outcome" }; const preview = await run("assistant", "run-preview", runInput); const queued = await run("assistant", "run-execute", { ...runInput, previewHash: preview.preview!.previewHash, approval, dryRun: false, idempotencyKey: "premium-ai-run-execute" }); expect(queued.records[0].data).toMatchObject({ platformPromptId: "premium.assistant.grounded-workbench", platformPromptVersion: "2026-08-24.1", platformPromptDigest: expect.stringMatching(/^[a-f0-9]{64}$/), output: null, confidence: null, requestedModelId: "local/audited", resultContract: { version: "premium-business-ai-result.v1", claimEvidenceRequired: true } });
    const completion = { output: { summary: "The project defines an outcome.", claims: [{ text: "The outcome is to ground claims.", evidenceIds: [source.id] }] }, confidence: 91, evidenceIds: [source.id], promptVersion: prompt.data.contentHash, modelId: "local/audited", reviewStatus: "pending-human-review" as const, approvalRequired: true as const };
    expect(() => validatePremiumBusinessAiCompletion({ ...completion, modelId: "different" }, { evidenceIds: [source.id], promptVersion: String(prompt.data.contentHash), modelId: "local/audited" })).toThrow(/provenance/);
    const claimed = await store.claimAiAction(); expect(claimed?.action.id).toBe(queued.aiAction?.id); await store.completeAiAction(claimed!.action.id, { status: "completed", result: completion }); await store.runInWorkspaceTransaction(userId, () => recordPremiumBusinessAiCompletion(store, auth, claimed!.action.id, undefined, deps));
    const reviewed = await run("assistant", "result-record", { runId: queued.records[0].id, output: completion.output, confidence: completion.confidence, evidenceIds: completion.evidenceIds, review: { status: "approved", reviewedBy: userId, reviewedAt: clock, notes: "Opened the cited source" }, approval, dryRun: false, idempotencyKey: "premium-result-record-01" }); expect(reviewed.records.find((record) => record.recordType === "ai-result")?.data).toMatchObject({ promptVersion: prompt.data.contentHash, modelId: "local/audited", confidence: 91, fabricatedOutputAllowed: false });
    const agentDraft = first(await run("assistant", "agent-draft", { name: "Planner", purpose: "Propose a planning action", promptVersionId: prompt.id, allowedActions: ["projects_issue_create"], maximumSteps: 3, idempotencyKey: "premium-agent-draft-001" })); const agent = first(await run("assistant", "agent-approve", { agentId: agentDraft.id, contentHash: agentDraft.data.contentHash, approval, dryRun: false, idempotencyKey: "premium-agent-approve-01" })); const agentRun = await run("assistant", "agent-execute", { agentId: agent.id, goal: "Propose next work", evidenceIds: [source.id], modelId: "local/audited", approval, dryRun: false, idempotencyKey: "premium-agent-execute-01" }); expect(agentRun.records[0].data).toMatchObject({ automaticMutationAllowed: false, proposalsRequireSeparateApproval: true, allowedActions: ["projects_issue_create"] });
    expect(await store.listRecords(userId, { moduleId: "assistant", recordType: "premium-command-receipt", limit: 100 })).toHaveLength(8);
  });
});
