export type CoreBusinessModuleId = "automate" | "publish" | "inbox" | "crm" | "tasks" | "feedback" | "knowledge" | "links";
export type CoreBusinessScope = "read" | "write" | "ai" | "external";
export type CoreBusinessOperation = "read" | "command" | "ai";
export type CoreBusinessRisk = "low" | "moderate" | "high";

export interface CoreBusinessJsonSchema {
  type: "object";
  required: string[];
  properties: Record<string, Record<string, unknown>>;
  additionalProperties: false;
}

export interface CoreBusinessActionDefinition {
  id: string;
  moduleId: CoreBusinessModuleId;
  productName: string;
  title: string;
  description: string;
  operation: CoreBusinessOperation;
  requiredScope: CoreBusinessScope;
  recordType: string;
  risk: CoreBusinessRisk;
  destructive: boolean;
  externalEffect: boolean;
  inputSchema: CoreBusinessJsonSchema;
  exampleInput: Record<string, unknown>;
  cliExample: string;
  mcpToolName: string;
  promptId?: string;
  promptVersion?: string;
}

const uuid = { type: "string", format: "uuid" };
const text = (maxLength = 4_000) => ({ type: "string", minLength: 1, maxLength });
const optionalText = (maxLength = 4_000) => ({ type: "string", maxLength });
const dateTime = { type: "string", format: "date-time" };
const sha256 = { type: "string", pattern: "^[a-f0-9]{64}$" };
const integer = (minimum = 0, maximum = Number.MAX_SAFE_INTEGER) => ({ type: "integer", minimum, maximum });
const stringArray = (maxItems = 100) => ({ type: "array", maxItems, items: text(500) });
const uuidArray = (maxItems = 100) => ({ type: "array", maxItems, items: uuid });
const object = { type: "object" };
const boolean = { type: "boolean" };
const url = { type: "string", format: "uri", pattern: "^https://" };
const idempotencyKey = { type: "string", pattern: "^[A-Za-z0-9._:-]{16,200}$" };
const approval = {
  type: "object",
  required: ["approved", "approvedBy", "approvedAt", "decisionId", "reason"],
  properties: {
    approved: { const: true },
    approvedBy: uuid,
    approvedAt: dateTime,
    decisionId: { type: "string", pattern: "^[A-Za-z0-9._:-]{16,200}$" },
    reason: text(1_000),
  },
  additionalProperties: false,
};

const sample = {
  actor: "00000000-0000-4000-8000-000000000001",
  workspace: "00000000-0000-4000-8000-000000000010",
  record: "00000000-0000-4000-8000-000000000100",
  evidence: "00000000-0000-4000-8000-000000000101",
};

type Draft = Omit<CoreBusinessActionDefinition, "cliExample" | "mcpToolName" | "inputSchema" | "destructive" | "externalEffect" | "risk" | "requiredScope"> & {
  requiredScope?: CoreBusinessScope;
  risk?: CoreBusinessRisk;
  destructive?: boolean;
  externalEffect?: boolean;
  required: string[];
  properties: Record<string, Record<string, unknown>>;
};

function define(draft: Draft): CoreBusinessActionDefinition {
  const { required: draftRequired, properties: draftProperties, requiredScope, risk, destructive: draftDestructive, externalEffect: draftExternalEffect, ...base } = draft;
  const mutates = draft.operation !== "read";
  const destructive = draftDestructive ?? false;
  const externalEffect = draftExternalEffect ?? false;
  const properties = { ...draftProperties };
  const required = [...draftRequired];
  const exampleInput = { ...draft.exampleInput };
  if (mutates) {
    properties.idempotencyKey = idempotencyKey;
    required.push("idempotencyKey");
    exampleInput.idempotencyKey = `${draft.moduleId}.${draft.id}.sample-0001`;
  }
  if (destructive || externalEffect) {
    properties.dryRun = boolean;
    properties.approval = approval;
    required.push("dryRun");
    exampleInput.dryRun = true;
  }
  const tool = `${draft.moduleId}_${draft.id.replaceAll("-", "_")}`;
  const cliInput = JSON.stringify(exampleInput).replaceAll("'", "'\\''");
  return {
    ...base,
    requiredScope: requiredScope ?? (draft.operation === "read" ? "read" : draft.operation === "ai" ? "ai" : externalEffect ? "external" : "write"),
    risk: risk ?? (destructive || externalEffect ? "high" : draft.operation === "ai" ? "moderate" : "low"),
    destructive,
    externalEffect,
    inputSchema: { type: "object", required: [...new Set(required)], properties, additionalProperties: false },
    exampleInput,
    cliExample: `supersuite action ${draft.moduleId} ${draft.id} '${cliInput}'`,
    mcpToolName: tool,
  };
}

const automate = [
  define({ moduleId: "automate", productName: "PulseFlow", id: "workflow-version-create", title: "Create typed workflow version", description: "Freeze a directed workflow graph with typed trigger, step, retry, and approval contracts.", operation: "command", recordType: "workflow-version", required: ["name", "triggerSchema", "steps"], properties: { name: text(160), triggerSchema: object, steps: { type: "array", minItems: 1, maxItems: 100, items: object } }, exampleInput: { name: "Lead intake", triggerSchema: { type: "object" }, steps: [{ key: "qualify", kind: "transform" }] } }),
  define({ moduleId: "automate", productName: "PulseFlow", id: "trigger-event-validate", title: "Validate trigger event", description: "Validate a candidate event against an immutable workflow trigger schema without starting a run.", operation: "read", recordType: "workflow-version", required: ["workflowVersionId", "event"], properties: { workflowVersionId: uuid, event: object }, exampleInput: { workflowVersionId: sample.record, event: { leadId: "lead-42" } } }),
  define({ moduleId: "automate", productName: "PulseFlow", id: "workflow-publish", title: "Publish workflow version", description: "Activate the exact content-addressed workflow version after a human approval.", operation: "command", recordType: "workflow-version", destructive: true, required: ["workflowVersionId", "contentHash"], properties: { workflowVersionId: uuid, contentHash: sha256 }, exampleInput: { workflowVersionId: sample.record, contentHash: "a".repeat(64) } }),
  define({ moduleId: "automate", productName: "PulseFlow", id: "workflow-run-simulate", title: "Simulate workflow run", description: "Evaluate step order, branch predicates, and budgets without connectors or external side effects.", operation: "command", recordType: "workflow-run", required: ["workflowVersionId", "event"], properties: { workflowVersionId: uuid, event: object }, exampleInput: { workflowVersionId: sample.record, event: { leadId: "lead-42" } } }),
  define({ moduleId: "automate", productName: "PulseFlow", id: "workflow-run-start", title: "Start approved workflow run", description: "Create a run and hand approved connector steps to an external executor with an immutable event snapshot.", operation: "command", recordType: "workflow-run", externalEffect: true, required: ["workflowVersionId", "event"], properties: { workflowVersionId: uuid, event: object }, exampleInput: { workflowVersionId: sample.record, event: { leadId: "lead-42" } } }),
  define({ moduleId: "automate", productName: "PulseFlow", id: "webhook-event-ingest", title: "Ingest signed webhook event", description: "Persist a deduplicated webhook envelope after signature verification at the hosting boundary.", operation: "command", recordType: "trigger-event", required: ["endpointId", "deliveryId", "bodyHash", "receivedAt"], properties: { endpointId: uuid, deliveryId: text(200), bodyHash: sha256, receivedAt: dateTime }, exampleInput: { endpointId: sample.record, deliveryId: "delivery-42", bodyHash: "b".repeat(64), receivedAt: "2026-08-24T12:00:00.000Z" } }),
  define({ moduleId: "automate", productName: "PulseFlow", id: "failure-diagnose", title: "Diagnose failed run", description: "Queue a cited root-cause proposal against selected run and step evidence; never retries automatically.", operation: "ai", recordType: "ai-request-audit", required: ["runId", "instruction", "evidenceIds"], properties: { runId: uuid, instruction: text(), evidenceIds: uuidArray() }, exampleInput: { runId: sample.record, instruction: "Explain the first causal failure.", evidenceIds: [sample.record, sample.evidence] }, promptId: "automate.failure-diagnose", promptVersion: "2026-08-24.1" }),
  define({ moduleId: "automate", productName: "PulseFlow", id: "retry-plan-propose", title: "Propose bounded retry plan", description: "Queue an evidence-backed retry plan with blast-radius and approval requirements.", operation: "ai", recordType: "ai-request-audit", required: ["runId", "instruction", "evidenceIds"], properties: { runId: uuid, instruction: text(), evidenceIds: uuidArray() }, exampleInput: { runId: sample.record, instruction: "Propose the smallest safe retry.", evidenceIds: [sample.record] }, promptId: "automate.retry-plan-propose", promptVersion: "2026-08-24.1" }),
  define({ moduleId: "automate", productName: "PulseFlow", id: "run-export", title: "Export run evidence", description: "Create a private canonical export manifest for one run, its steps, and immutable receipts.", operation: "command", recordType: "export-job", required: ["runId", "format"], properties: { runId: uuid, format: { enum: ["canonical-json", "csv"] } }, exampleInput: { runId: sample.record, format: "canonical-json" } }),
];

const publish = [
  define({ moduleId: "publish", productName: "SignalDeck", id: "channel-binding-preview", title: "Preview channel binding", description: "Validate a channel capability manifest without storing provider tokens or calling the provider.", operation: "read", recordType: "channel-binding", required: ["provider", "accountRef", "capabilities"], properties: { provider: text(80), accountRef: text(200), capabilities: stringArray(50) }, exampleInput: { provider: "federated-social", accountRef: "brand-main", capabilities: ["text", "image"] } }),
  define({ moduleId: "publish", productName: "SignalDeck", id: "campaign-draft", title: "Create campaign brief", description: "Create a goal, audience, channel, consent, and measurement brief before content exists.", operation: "command", recordType: "campaign", required: ["name", "goal", "audience", "channelIds"], properties: { name: text(160), goal: text(1_000), audience: text(1_000), channelIds: uuidArray(50) }, exampleInput: { name: "Launch week", goal: "Qualified product visits", audience: "Existing opt-in customers", channelIds: [sample.record] } }),
  define({ moduleId: "publish", productName: "SignalDeck", id: "content-variants-propose", title: "Propose cited content variants", description: "Queue channel-aware variants grounded in an approved campaign brief and selected evidence.", operation: "ai", recordType: "ai-request-audit", required: ["campaignId", "instruction", "evidenceIds"], properties: { campaignId: uuid, instruction: text(), evidenceIds: uuidArray() }, exampleInput: { campaignId: sample.record, instruction: "Draft three factual launch angles.", evidenceIds: [sample.evidence] }, promptId: "publish.content-variants-propose", promptVersion: "2026-08-24.1" }),
  define({ moduleId: "publish", productName: "SignalDeck", id: "campaign-approve", title: "Approve campaign snapshot", description: "Approve the exact campaign and content snapshot without publishing it.", operation: "command", recordType: "campaign", required: ["campaignId", "contentHash"], properties: { campaignId: uuid, contentHash: sha256 }, exampleInput: { campaignId: sample.record, contentHash: "c".repeat(64) } }),
  define({ moduleId: "publish", productName: "SignalDeck", id: "post-schedule", title: "Schedule approved post", description: "Bind exact approved content to a channel and UTC delivery window with no provider call.", operation: "command", recordType: "scheduled-post", required: ["campaignId", "channelId", "content", "scheduledAt", "campaignHash"], properties: { campaignId: uuid, channelId: uuid, content: text(20_000), scheduledAt: dateTime, campaignHash: sha256 }, exampleInput: { campaignId: sample.record, channelId: sample.evidence, content: "Launch details", scheduledAt: "2026-08-25T15:00:00.000Z", campaignHash: "c".repeat(64) } }),
  define({ moduleId: "publish", productName: "SignalDeck", id: "publication-dispatch", title: "Dispatch scheduled publication", description: "Send one exact approved post through a configured provider executor and store its receipt.", operation: "command", recordType: "publication-delivery", externalEffect: true, required: ["scheduledPostId"], properties: { scheduledPostId: uuid }, exampleInput: { scheduledPostId: sample.record } }),
  define({ moduleId: "publish", productName: "SignalDeck", id: "metrics-import", title: "Import channel metrics", description: "Append a provider-attributed metric observation with measurement time and source provenance.", operation: "command", recordType: "metric-observation", required: ["scheduledPostId", "observedAt", "source", "metrics"], properties: { scheduledPostId: uuid, observedAt: dateTime, source: text(120), metrics: object }, exampleInput: { scheduledPostId: sample.record, observedAt: "2026-08-26T15:00:00.000Z", source: "provider-export", metrics: { views: 120 } } }),
  define({ moduleId: "publish", productName: "SignalDeck", id: "performance-explain", title: "Explain campaign performance", description: "Queue an exposure-aware analysis that cites exact observations and separates facts from hypotheses.", operation: "ai", recordType: "ai-request-audit", required: ["campaignId", "instruction", "evidenceIds"], properties: { campaignId: uuid, instruction: text(), evidenceIds: uuidArray() }, exampleInput: { campaignId: sample.record, instruction: "Explain measured changes without causal overclaiming.", evidenceIds: [sample.evidence] }, promptId: "publish.performance-explain", promptVersion: "2026-08-24.1" }),
  define({ moduleId: "publish", productName: "SignalDeck", id: "campaign-export", title: "Export campaign ledger", description: "Create a private export of briefs, approvals, exact copy, deliveries, and metric clocks.", operation: "command", recordType: "export-job", required: ["campaignId", "format"], properties: { campaignId: uuid, format: { enum: ["canonical-json", "csv"] } }, exampleInput: { campaignId: sample.record, format: "canonical-json" } }),
];

const inbox = [
  define({ moduleId: "inbox", productName: "RelayDesk", id: "thread-open", title: "Open support thread", description: "Open a customer thread with channel, contact, subject, and first-message provenance.", operation: "command", recordType: "conversation", required: ["contactId", "channel", "subject", "message"], properties: { contactId: uuid, channel: text(40), subject: text(300), message: text(20_000) }, exampleInput: { contactId: sample.record, channel: "email", subject: "Invoice question", message: "Please clarify the total." } }),
  define({ moduleId: "inbox", productName: "RelayDesk", id: "message-ingest", title: "Ingest inbound message", description: "Append a deduplicated inbound message envelope while preserving provider and consent provenance.", operation: "command", recordType: "message", required: ["conversationId", "deliveryId", "senderRef", "body", "receivedAt"], properties: { conversationId: uuid, deliveryId: text(200), senderRef: text(200), body: text(20_000), receivedAt: dateTime }, exampleInput: { conversationId: sample.record, deliveryId: "mail-42", senderRef: "customer-42", body: "Following up", receivedAt: "2026-08-24T12:00:00.000Z" } }),
  define({ moduleId: "inbox", productName: "RelayDesk", id: "thread-assign", title: "Assign support owner", description: "Assign an open thread with an expected-version guard and append an audit event.", operation: "command", recordType: "conversation", required: ["conversationId", "assigneeId", "expectedVersion"], properties: { conversationId: uuid, assigneeId: uuid, expectedVersion: integer(1) }, exampleInput: { conversationId: sample.record, assigneeId: sample.actor, expectedVersion: 1 } }),
  define({ moduleId: "inbox", productName: "RelayDesk", id: "sla-policy-set", title: "Set SLA policy", description: "Create an explicit priority-to-response-time policy with business-hour metadata.", operation: "command", recordType: "sla-policy", required: ["name", "targets", "timeZone"], properties: { name: text(160), targets: object, timeZone: text(100) }, exampleInput: { name: "Standard", targets: { normalMinutes: 480, urgentMinutes: 60 }, timeZone: "America/New_York" } }),
  define({ moduleId: "inbox", productName: "RelayDesk", id: "reply-propose", title: "Propose grounded reply", description: "Queue a reply draft that cites selected thread and knowledge records and cannot send itself.", operation: "ai", recordType: "ai-request-audit", required: ["conversationId", "instruction", "evidenceIds"], properties: { conversationId: uuid, instruction: text(), evidenceIds: uuidArray() }, exampleInput: { conversationId: sample.record, instruction: "Draft a concise answer grounded in policy.", evidenceIds: [sample.record, sample.evidence] }, promptId: "inbox.reply-propose", promptVersion: "2026-08-24.1" }),
  define({ moduleId: "inbox", productName: "RelayDesk", id: "reply-send", title: "Send approved reply", description: "Send exact human-approved reply text through a configured channel and persist provider evidence.", operation: "command", recordType: "message", externalEffect: true, required: ["conversationId", "body", "proposalId"], properties: { conversationId: uuid, body: text(20_000), proposalId: { anyOf: [uuid, { type: "null" }] } }, exampleInput: { conversationId: sample.record, body: "Here is the confirmed answer.", proposalId: null } }),
  define({ moduleId: "inbox", productName: "RelayDesk", id: "thread-summarize", title: "Summarize thread with citations", description: "Queue a chronology, commitments, unanswered questions, confidence, and source citations.", operation: "ai", recordType: "ai-request-audit", required: ["conversationId", "instruction", "evidenceIds"], properties: { conversationId: uuid, instruction: text(), evidenceIds: uuidArray() }, exampleInput: { conversationId: sample.record, instruction: "Summarize only supported facts.", evidenceIds: [sample.record] }, promptId: "inbox.thread-summarize", promptVersion: "2026-08-24.1" }),
  define({ moduleId: "inbox", productName: "RelayDesk", id: "thread-resolve", title: "Resolve support thread", description: "Resolve an open thread with outcome, reason, and expected version while retaining the message ledger.", operation: "command", recordType: "conversation", required: ["conversationId", "expectedVersion", "resolution"], properties: { conversationId: uuid, expectedVersion: integer(1), resolution: text(2_000) }, exampleInput: { conversationId: sample.record, expectedVersion: 2, resolution: "Customer confirmed the answer." } }),
  define({ moduleId: "inbox", productName: "RelayDesk", id: "conversation-export", title: "Export support thread", description: "Create a private redaction-aware export manifest for a thread and its append-only messages.", operation: "command", recordType: "export-job", required: ["conversationId", "redactionPolicy"], properties: { conversationId: uuid, redactionPolicy: { enum: ["none", "mask-contact", "content-only"] } }, exampleInput: { conversationId: sample.record, redactionPolicy: "mask-contact" } }),
];

const crm = [
  define({ moduleId: "crm", productName: "OrbitCRM", id: "account-upsert", title: "Upsert organization account", description: "Create or reconcile an account by an explicit external key without fuzzy autonomous merging.", operation: "command", recordType: "account", required: ["externalKey", "name", "domain"], properties: { externalKey: text(200), name: text(200), domain: text(253) }, exampleInput: { externalKey: "acct-42", name: "Northwind", domain: "northwind.example" } }),
  define({ moduleId: "crm", productName: "OrbitCRM", id: "contact-link", title: "Link contact to account", description: "Create a consent-aware contact identity and link it to one owned account.", operation: "command", recordType: "contact", required: ["accountId", "name", "email", "consentBasis"], properties: { accountId: uuid, name: text(200), email: { type: "string", format: "email" }, consentBasis: text(500) }, exampleInput: { accountId: sample.record, name: "Avery", email: "avery@example.com", consentBasis: "Existing customer" } }),
  define({ moduleId: "crm", productName: "OrbitCRM", id: "opportunity-open", title: "Open qualified opportunity", description: "Open a currency-safe opportunity with amount in integer minor units and an explicit close hypothesis.", operation: "command", recordType: "opportunity", required: ["accountId", "name", "amountMinor", "currency", "expectedCloseAt"], properties: { accountId: uuid, name: text(200), amountMinor: integer(0), currency: { type: "string", pattern: "^[A-Z]{3}$" }, expectedCloseAt: dateTime }, exampleInput: { accountId: sample.record, name: "Expansion", amountMinor: 250000, currency: "USD", expectedCloseAt: "2026-10-01T00:00:00.000Z" } }),
  define({ moduleId: "crm", productName: "OrbitCRM", id: "opportunity-transition", title: "Transition opportunity stage", description: "Move an opportunity through an allowed pipeline edge using optimistic version control.", operation: "command", recordType: "opportunity", required: ["opportunityId", "toStage", "expectedVersion", "reason"], properties: { opportunityId: uuid, toStage: { enum: ["qualified", "evaluation", "proposal", "won", "lost"] }, expectedVersion: integer(1), reason: text(1_000) }, exampleInput: { opportunityId: sample.record, toStage: "evaluation", expectedVersion: 1, reason: "Discovery completed" } }),
  define({ moduleId: "crm", productName: "OrbitCRM", id: "activity-record", title: "Record customer activity", description: "Append a timestamped interaction fact without rewriting historical relationship data.", operation: "command", recordType: "activity", required: ["accountId", "kind", "occurredAt", "summary"], properties: { accountId: uuid, kind: { enum: ["call", "email", "meeting", "note"] }, occurredAt: dateTime, summary: text(4_000) }, exampleInput: { accountId: sample.record, kind: "meeting", occurredAt: "2026-08-24T12:00:00.000Z", summary: "Reviewed deployment needs." } }),
  define({ moduleId: "crm", productName: "OrbitCRM", id: "duplicate-review-propose", title: "Propose duplicate review", description: "Queue explainable candidate matches with field-level evidence; never merges records automatically.", operation: "ai", recordType: "ai-request-audit", required: ["recordId", "instruction", "evidenceIds"], properties: { recordId: uuid, instruction: text(), evidenceIds: uuidArray() }, exampleInput: { recordId: sample.record, instruction: "Find likely duplicates and explain each signal.", evidenceIds: [sample.record, sample.evidence] }, promptId: "crm.duplicate-review-propose", promptVersion: "2026-08-24.1" }),
  define({ moduleId: "crm", productName: "OrbitCRM", id: "next-action-propose", title: "Propose next relationship action", description: "Queue an evidence-backed follow-up plan with uncertainty and no autonomous outreach.", operation: "ai", recordType: "ai-request-audit", required: ["accountId", "instruction", "evidenceIds"], properties: { accountId: uuid, instruction: text(), evidenceIds: uuidArray() }, exampleInput: { accountId: sample.record, instruction: "Suggest the smallest useful next step.", evidenceIds: [sample.record] }, promptId: "crm.next-action-propose", promptVersion: "2026-08-24.1" }),
  define({ moduleId: "crm", productName: "OrbitCRM", id: "pipeline-forecast", title: "Compute transparent pipeline forecast", description: "Calculate deterministic weighted totals from explicit stage probabilities and integer minor units.", operation: "read", recordType: "opportunity", required: ["currency", "stageProbabilities"], properties: { currency: { type: "string", pattern: "^[A-Z]{3}$" }, stageProbabilities: object }, exampleInput: { currency: "USD", stageProbabilities: { qualified: 0.2, evaluation: 0.4, proposal: 0.7 } } }),
  define({ moduleId: "crm", productName: "OrbitCRM", id: "crm-export", title: "Export CRM graph", description: "Create a private canonical graph export with account, contact, opportunity, and activity links.", operation: "command", recordType: "export-job", required: ["accountIds", "format"], properties: { accountIds: uuidArray(1_000), format: { enum: ["canonical-json", "csv-bundle"] } }, exampleInput: { accountIds: [sample.record], format: "canonical-json" } }),
];

const tasks = [
  define({ moduleId: "tasks", productName: "Northstar Work", id: "project-blueprint-create", title: "Create project blueprint", description: "Create a project with explicit workflow states, work limits, owners, and finish conditions.", operation: "command", recordType: "project", required: ["name", "states", "workInProgressLimits"], properties: { name: text(200), states: stringArray(30), workInProgressLimits: object }, exampleInput: { name: "Product launch", states: ["backlog", "doing", "review", "done"], workInProgressLimits: { doing: 3 } } }),
  define({ moduleId: "tasks", productName: "Northstar Work", id: "work-item-create", title: "Create scoped work item", description: "Create an owned work item with acceptance criteria, priority, and optional due date.", operation: "command", recordType: "work-item", required: ["projectId", "title", "acceptanceCriteria", "priority"], properties: { projectId: uuid, title: text(300), acceptanceCriteria: stringArray(50), priority: { enum: ["low", "normal", "high", "urgent"] }, dueAt: dateTime }, exampleInput: { projectId: sample.record, title: "Verify billing flow", acceptanceCriteria: ["Test webhook replay"], priority: "high" } }),
  define({ moduleId: "tasks", productName: "Northstar Work", id: "dependency-link", title: "Link work dependency", description: "Add an acyclic predecessor edge after checking the full project dependency graph.", operation: "command", recordType: "work-item-dependency", required: ["projectId", "predecessorId", "successorId"], properties: { projectId: uuid, predecessorId: uuid, successorId: uuid }, exampleInput: { projectId: sample.record, predecessorId: sample.record, successorId: sample.evidence } }),
  define({ moduleId: "tasks", productName: "Northstar Work", id: "work-item-transition", title: "Transition work item", description: "Apply one allowed project-state edge with expected version, work-limit, and dependency checks.", operation: "command", recordType: "work-item", required: ["workItemId", "toState", "expectedVersion"], properties: { workItemId: uuid, toState: text(80), expectedVersion: integer(1) }, exampleInput: { workItemId: sample.record, toState: "doing", expectedVersion: 1 } }),
  define({ moduleId: "tasks", productName: "Northstar Work", id: "sprint-commit", title: "Commit sprint scope", description: "Freeze a time-boxed scope snapshot so later additions remain visible as scope changes.", operation: "command", recordType: "sprint", required: ["projectId", "name", "startsAt", "endsAt", "workItemIds"], properties: { projectId: uuid, name: text(160), startsAt: dateTime, endsAt: dateTime, workItemIds: uuidArray(500) }, exampleInput: { projectId: sample.record, name: "Sprint 12", startsAt: "2026-08-25T00:00:00.000Z", endsAt: "2026-09-08T00:00:00.000Z", workItemIds: [sample.evidence] } }),
  define({ moduleId: "tasks", productName: "Northstar Work", id: "workload-rebalance-propose", title: "Propose workload rebalance", description: "Queue a capacity-aware reassignment proposal that cites owned work and never changes assignees.", operation: "ai", recordType: "ai-request-audit", required: ["projectId", "instruction", "evidenceIds"], properties: { projectId: uuid, instruction: text(), evidenceIds: uuidArray(500) }, exampleInput: { projectId: sample.record, instruction: "Reduce overload without moving urgent work.", evidenceIds: [sample.evidence] }, promptId: "tasks.workload-rebalance-propose", promptVersion: "2026-08-24.1" }),
  define({ moduleId: "tasks", productName: "Northstar Work", id: "delivery-risk-explain", title: "Explain delivery risk", description: "Queue a cited risk analysis that distinguishes observed blockers from uncertain predictions.", operation: "ai", recordType: "ai-request-audit", required: ["projectId", "instruction", "evidenceIds"], properties: { projectId: uuid, instruction: text(), evidenceIds: uuidArray(500) }, exampleInput: { projectId: sample.record, instruction: "Explain schedule risk and confidence.", evidenceIds: [sample.evidence] }, promptId: "tasks.delivery-risk-explain", promptVersion: "2026-08-24.1" }),
  define({ moduleId: "tasks", productName: "Northstar Work", id: "time-log", title: "Log bounded work time", description: "Append a nonnegative whole-minute work interval linked to one item and actor.", operation: "command", recordType: "time-entry", required: ["workItemId", "startedAt", "endedAt"], properties: { workItemId: uuid, startedAt: dateTime, endedAt: dateTime, note: optionalText(1_000) }, exampleInput: { workItemId: sample.record, startedAt: "2026-08-24T12:00:00.000Z", endedAt: "2026-08-24T13:00:00.000Z", note: "Verification" } }),
  define({ moduleId: "tasks", productName: "Northstar Work", id: "project-export", title: "Export project ledger", description: "Create a canonical project export with states, dependencies, scope changes, and history.", operation: "command", recordType: "export-job", required: ["projectId", "format"], properties: { projectId: uuid, format: { enum: ["canonical-json", "csv-bundle"] } }, exampleInput: { projectId: sample.record, format: "canonical-json" } }),
];

const feedback = [
  define({ moduleId: "feedback", productName: "IdeaLoop", id: "board-create", title: "Create feedback board", description: "Create a public/private request board with explicit visibility, voting, and moderation rules.", operation: "command", recordType: "feedback-board", required: ["name", "visibility", "votingPolicy"], properties: { name: text(160), visibility: { enum: ["private", "public"] }, votingPolicy: { enum: ["members", "verified-submitters", "public"] } }, exampleInput: { name: "Product ideas", visibility: "public", votingPolicy: "verified-submitters" } }),
  define({ moduleId: "feedback", productName: "IdeaLoop", id: "request-submit", title: "Submit evidence-linked request", description: "Capture a request, submitter consent, problem statement, and optional customer evidence.", operation: "command", recordType: "feedback-request", required: ["boardId", "title", "problem", "consent"], properties: { boardId: uuid, title: text(300), problem: text(10_000), consent: boolean }, exampleInput: { boardId: sample.record, title: "Bulk export", problem: "Exporting projects one by one is slow.", consent: true } }),
  define({ moduleId: "feedback", productName: "IdeaLoop", id: "vote-cast", title: "Cast deduplicated vote", description: "Record one pseudonymous voter decision per request without inflating counts on retries.", operation: "command", recordType: "feedback-vote", required: ["requestId", "voterKeyHash", "decision"], properties: { requestId: uuid, voterKeyHash: sha256, decision: { enum: ["up", "withdraw"] } }, exampleInput: { requestId: sample.record, voterKeyHash: "d".repeat(64), decision: "up" } }),
  define({ moduleId: "feedback", productName: "IdeaLoop", id: "duplicate-cluster-propose", title: "Propose duplicate clusters", description: "Queue explainable semantic clusters with exact request citations; never merges or hides requests.", operation: "ai", recordType: "ai-request-audit", required: ["boardId", "instruction", "evidenceIds"], properties: { boardId: uuid, instruction: text(), evidenceIds: uuidArray(1_000) }, exampleInput: { boardId: sample.record, instruction: "Find requests describing the same user problem.", evidenceIds: [sample.evidence] }, promptId: "feedback.duplicate-cluster-propose", promptVersion: "2026-08-24.1" }),
  define({ moduleId: "feedback", productName: "IdeaLoop", id: "request-merge", title: "Merge reviewed requests", description: "Redirect duplicate requests to one canonical request while preserving every submission and vote ledger.", operation: "command", recordType: "feedback-request", destructive: true, required: ["sourceRequestIds", "targetRequestId", "reason"], properties: { sourceRequestIds: uuidArray(100), targetRequestId: uuid, reason: text(2_000) }, exampleInput: { sourceRequestIds: [sample.evidence], targetRequestId: sample.record, reason: "Reviewed as the same user problem." } }),
  define({ moduleId: "feedback", productName: "IdeaLoop", id: "status-transition", title: "Transition request status", description: "Move one request through an explicit roadmap state with expected version and a public explanation.", operation: "command", recordType: "feedback-request", required: ["requestId", "toStatus", "expectedVersion", "explanation"], properties: { requestId: uuid, toStatus: { enum: ["open", "planned", "in-progress", "shipped", "declined"] }, expectedVersion: integer(1), explanation: text(2_000) }, exampleInput: { requestId: sample.record, toStatus: "planned", expectedVersion: 1, explanation: "Accepted for the next planning cycle." } }),
  define({ moduleId: "feedback", productName: "IdeaLoop", id: "changelog-publish", title: "Publish changelog update", description: "Publish an exact reviewed update for shipped requests through a configured public surface.", operation: "command", recordType: "changelog-entry", externalEffect: true, required: ["requestIds", "title", "body"], properties: { requestIds: uuidArray(100), title: text(300), body: text(20_000) }, exampleInput: { requestIds: [sample.record], title: "Bulk export shipped", body: "Projects can now be exported together." } }),
  define({ moduleId: "feedback", productName: "IdeaLoop", id: "impact-score", title: "Compute transparent impact score", description: "Compute an inspectable integer score from votes, affected accounts, urgency, and effort inputs.", operation: "read", recordType: "feedback-request", required: ["requestId", "weights"], properties: { requestId: uuid, weights: object }, exampleInput: { requestId: sample.record, weights: { votes: 1, accounts: 5, urgency: 3, effort: -2 } } }),
  define({ moduleId: "feedback", productName: "IdeaLoop", id: "feedback-export", title: "Export feedback ledger", description: "Create a consent-aware export of requests, votes, merges, statuses, and changelog links.", operation: "command", recordType: "export-job", required: ["boardId", "format"], properties: { boardId: uuid, format: { enum: ["canonical-json", "csv-bundle"] } }, exampleInput: { boardId: sample.record, format: "canonical-json" } }),
];

const knowledge = [
  define({ moduleId: "knowledge", productName: "AtlasBase", id: "library-create", title: "Create governed library", description: "Create a knowledge library with ownership, default access, locale, and review cadence.", operation: "command", recordType: "knowledge-library", required: ["name", "defaultAccess", "locale", "reviewCadenceDays"], properties: { name: text(200), defaultAccess: { enum: ["private", "workspace", "public"] }, locale: text(20), reviewCadenceDays: integer(1, 3_650) }, exampleInput: { name: "Support handbook", defaultAccess: "workspace", locale: "en-US", reviewCadenceDays: 90 } }),
  define({ moduleId: "knowledge", productName: "AtlasBase", id: "page-revision-draft", title: "Draft immutable page revision", description: "Create a content-addressed page revision with explicit source links and parent revision.", operation: "command", recordType: "page-revision", required: ["libraryId", "title", "content", "sourceIds"], properties: { libraryId: uuid, title: text(300), content: text(100_000), sourceIds: uuidArray(500), parentRevisionId: uuid }, exampleInput: { libraryId: sample.record, title: "Refund policy", content: "Reviewed policy content", sourceIds: [sample.evidence] } }),
  define({ moduleId: "knowledge", productName: "AtlasBase", id: "page-revision-publish", title: "Publish exact page revision", description: "Publish a reviewed content hash to its configured audience without rewriting prior revisions.", operation: "command", recordType: "page-revision", externalEffect: true, required: ["revisionId", "contentHash"], properties: { revisionId: uuid, contentHash: sha256 }, exampleInput: { revisionId: sample.record, contentHash: "e".repeat(64) } }),
  define({ moduleId: "knowledge", productName: "AtlasBase", id: "source-link", title: "Link verifiable source", description: "Attach a source locator, observation time, content hash, and trust note to a page revision.", operation: "command", recordType: "knowledge-source", required: ["revisionId", "locator", "observedAt", "contentHash", "trustNote"], properties: { revisionId: uuid, locator: text(2_000), observedAt: dateTime, contentHash: sha256, trustNote: text(1_000) }, exampleInput: { revisionId: sample.record, locator: "internal-policy-42", observedAt: "2026-08-24T12:00:00.000Z", contentHash: "f".repeat(64), trustNote: "Approved policy record" } }),
  define({ moduleId: "knowledge", productName: "AtlasBase", id: "answer-propose", title: "Propose cited knowledge answer", description: "Queue an answer constrained to selected published revisions with per-claim citations and abstention.", operation: "ai", recordType: "ai-request-audit", required: ["question", "evidenceIds"], properties: { question: text(4_000), evidenceIds: uuidArray(500) }, exampleInput: { question: "What is the refund window?", evidenceIds: [sample.evidence] }, promptId: "knowledge.answer-propose", promptVersion: "2026-08-24.1" }),
  define({ moduleId: "knowledge", productName: "AtlasBase", id: "staleness-audit-propose", title: "Propose staleness audit", description: "Queue a source-clock comparison that flags unsupported or expired claims without editing pages.", operation: "ai", recordType: "ai-request-audit", required: ["libraryId", "instruction", "evidenceIds"], properties: { libraryId: uuid, instruction: text(), evidenceIds: uuidArray(1_000) }, exampleInput: { libraryId: sample.record, instruction: "Find claims whose sources are older than policy.", evidenceIds: [sample.evidence] }, promptId: "knowledge.staleness-audit-propose", promptVersion: "2026-08-24.1" }),
  define({ moduleId: "knowledge", productName: "AtlasBase", id: "permission-grant", title: "Grant scoped library access", description: "Grant view or edit access to one workspace principal with expiry and no public token.", operation: "command", recordType: "knowledge-grant", required: ["libraryId", "principalId", "permission", "expiresAt"], properties: { libraryId: uuid, principalId: uuid, permission: { enum: ["view", "edit"] }, expiresAt: dateTime }, exampleInput: { libraryId: sample.record, principalId: sample.actor, permission: "view", expiresAt: "2027-08-24T12:00:00.000Z" } }),
  define({ moduleId: "knowledge", productName: "AtlasBase", id: "page-export", title: "Export exact page revision", description: "Create a pinned export manifest for one immutable revision and its source bibliography.", operation: "command", recordType: "export-job", required: ["revisionId", "format"], properties: { revisionId: uuid, format: { enum: ["canonical-json", "markdown", "html", "pdf"] } }, exampleInput: { revisionId: sample.record, format: "markdown" } }),
  define({ moduleId: "knowledge", productName: "AtlasBase", id: "import-preview", title: "Preview knowledge import", description: "Validate a bounded import manifest, links, hashes, and conflicts without creating pages.", operation: "read", recordType: "import-preview", required: ["libraryId", "manifest"], properties: { libraryId: uuid, manifest: object }, exampleInput: { libraryId: sample.record, manifest: { pages: [] } } }),
];

const links = [
  define({ moduleId: "links", productName: "RouteKit", id: "route-create", title: "Create branded route", description: "Reserve a workspace route with explicit hostname, slug, privacy, and redirect policy.", operation: "command", recordType: "link-route", required: ["hostname", "slug", "privacyMode"], properties: { hostname: text(253), slug: { type: "string", pattern: "^[a-z0-9](?:[a-z0-9-]{0,62})$" }, privacyMode: { enum: ["aggregate", "consented-events", "no-analytics"] } }, exampleInput: { hostname: "go.example.com", slug: "launch", privacyMode: "aggregate" } }),
  define({ moduleId: "links", productName: "RouteKit", id: "destination-version-create", title: "Create destination version", description: "Create an immutable HTTPS destination snapshot with safety and campaign metadata.", operation: "command", recordType: "destination-version", required: ["routeId", "destination", "campaign"], properties: { routeId: uuid, destination: url, campaign: object }, exampleInput: { routeId: sample.record, destination: "https://example.com/launch", campaign: { source: "qr" } } }),
  define({ moduleId: "links", productName: "RouteKit", id: "destination-publish", title: "Publish destination version", description: "Atomically point a route to an exact reviewed destination hash while retaining rollback history.", operation: "command", recordType: "link-route", externalEffect: true, required: ["routeId", "destinationVersionId", "contentHash"], properties: { routeId: uuid, destinationVersionId: uuid, contentHash: sha256 }, exampleInput: { routeId: sample.record, destinationVersionId: sample.evidence, contentHash: "a".repeat(64) } }),
  define({ moduleId: "links", productName: "RouteKit", id: "redirect-resolve", title: "Resolve active redirect", description: "Resolve the exact active destination and policy for a route without recording a visitor event.", operation: "read", recordType: "link-route", required: ["routeId"], properties: { routeId: uuid }, exampleInput: { routeId: sample.record } }),
  define({ moduleId: "links", productName: "RouteKit", id: "event-ingest", title: "Ingest privacy-safe link event", description: "Append a consent-compatible event with coarse metadata and no raw IP or fingerprint.", operation: "command", recordType: "link-event", required: ["routeId", "eventId", "occurredAt", "kind", "dimensions"], properties: { routeId: uuid, eventId: text(200), occurredAt: dateTime, kind: { enum: ["redirect", "conversion"] }, dimensions: object }, exampleInput: { routeId: sample.record, eventId: "event-42", occurredAt: "2026-08-24T12:00:00.000Z", kind: "redirect", dimensions: { country: "US" } } }),
  define({ moduleId: "links", productName: "RouteKit", id: "experiment-allocate", title: "Allocate deterministic route experiment", description: "Assign a pseudonymous key to a weighted destination using a stable content-addressed hash.", operation: "read", recordType: "route-experiment", required: ["experimentId", "visitorKeyHash", "variants"], properties: { experimentId: uuid, visitorKeyHash: sha256, variants: { type: "array", minItems: 2, maxItems: 20, items: object } }, exampleInput: { experimentId: sample.record, visitorKeyHash: "b".repeat(64), variants: [{ key: "a", weight: 1 }, { key: "b", weight: 1 }] } }),
  define({ moduleId: "links", productName: "RouteKit", id: "destination-risk-propose", title: "Propose destination risk review", description: "Queue a cited safety review of destination evidence; never blocks or publishes a route autonomously.", operation: "ai", recordType: "ai-request-audit", required: ["destinationVersionId", "instruction", "evidenceIds"], properties: { destinationVersionId: uuid, instruction: text(), evidenceIds: uuidArray() }, exampleInput: { destinationVersionId: sample.record, instruction: "Review redirect risk and cite observations.", evidenceIds: [sample.evidence] }, promptId: "links.destination-risk-propose", promptVersion: "2026-08-24.1" }),
  define({ moduleId: "links", productName: "RouteKit", id: "route-disable", title: "Disable active route", description: "Disable redirect resolution immediately while retaining historical versions and aggregate events.", operation: "command", recordType: "link-route", destructive: true, required: ["routeId", "reason"], properties: { routeId: uuid, reason: text(1_000) }, exampleInput: { routeId: sample.record, reason: "Destination ownership changed." } }),
  define({ moduleId: "links", productName: "RouteKit", id: "analytics-export", title: "Export privacy-safe route analytics", description: "Create an aggregate export with observation clocks, suppression policy, and no raw visitor identifiers.", operation: "command", recordType: "export-job", required: ["routeIds", "from", "to", "format"], properties: { routeIds: uuidArray(500), from: dateTime, to: dateTime, format: { enum: ["canonical-json", "csv"] } }, exampleInput: { routeIds: [sample.record], from: "2026-08-01T00:00:00.000Z", to: "2026-08-24T00:00:00.000Z", format: "csv" } }),
];

export const coreBusinessActions: CoreBusinessActionDefinition[] = [...automate, ...publish, ...inbox, ...crm, ...tasks, ...feedback, ...knowledge, ...links];
export const coreBusinessActionsByModule = new Map<CoreBusinessModuleId, CoreBusinessActionDefinition[]>(
  (["automate", "publish", "inbox", "crm", "tasks", "feedback", "knowledge", "links"] as CoreBusinessModuleId[])
    .map((moduleId) => [moduleId, coreBusinessActions.filter((action) => action.moduleId === moduleId)]),
);
export const coreBusinessActionByKey = new Map(coreBusinessActions.map((action) => [`${action.moduleId}:${action.id}`, action]));

export function coreBusinessAction(moduleId: string, actionId: string) {
  return coreBusinessActionByKey.get(`${moduleId}:${actionId}`);
}
