export type AdditiveWaveTwoPlanId = "none" | "starter" | "scale" | "fleet";
export type AdditiveWaveTwoModuleId = "events" | "people" | "metering" | "assurance" | "live";
export type AdditiveWaveTwoOperation = "read" | "mutation" | "ai";
export type AdditiveWaveTwoScope = "read" | "write" | "ai";
export type AdditiveWaveTwoRisk = "low" | "medium" | "high" | "critical";
export type AdditiveWaveTwoExternalEffect = "none" | "publication" | "financial" | "access" | "employment" | "consent" | "moderation" | "broadcast" | "model";
export type AdditiveWaveTwoRole = "viewer" | "member" | "admin" | "owner";

export interface AdditiveWaveTwoJsonSchema {
  type: "object";
  required: readonly string[];
  properties: Readonly<Record<string, Readonly<Record<string, unknown>>>>;
  additionalProperties: false;
}

export interface AdditiveWaveTwoModuleDefinition {
  id: AdditiveWaveTwoModuleId;
  name: string;
  category: string;
  originalProductThesis: string;
  minPlan: Extract<AdditiveWaveTwoPlanId, "scale" | "fleet">;
  minimumMonthlyPlanUsd: 50 | 200;
  dataPlane: "workspace-shared";
  resource: {
    class: "high" | "accelerated";
    minimumCpuMillicores: number;
    minimumMemoryMiB: number;
    includedStorageGb: number;
    recommendedWorkerConcurrency: number;
  };
  aiNativeQualities: readonly string[];
}

export interface AdditiveWaveTwoActionDefinition {
  id: string;
  moduleId: AdditiveWaveTwoModuleId;
  productName: string;
  title: string;
  description: string;
  operation: AdditiveWaveTwoOperation;
  requiredScope: AdditiveWaveTwoScope;
  minimumRole: AdditiveWaveTwoRole;
  risk: AdditiveWaveTwoRisk;
  destructive: boolean;
  externalEffect: AdditiveWaveTwoExternalEffect;
  requiresApproval: boolean;
  supportsDryRun: boolean;
  idempotent: boolean;
  effectBoundary: "tenant-record" | "approved-ledger-command" | "proposal-only" | "read-only";
  recordType: string;
  inputSchema: AdditiveWaveTwoJsonSchema;
  exampleInput: Record<string, unknown>;
  cliExample: string;
  mcpToolName: string;
  promptId?: string;
  promptVersion?: string;
}

export const additiveWaveTwoModules = [
  {
    id: "events",
    name: "GatherLedger",
    category: "Events and ticketing",
    originalProductThesis: "Treat releases, inventory, money receipts, tickets, access, and attendee proposals as one auditable event ledger.",
    minPlan: "scale",
    minimumMonthlyPlanUsd: 50,
    dataPlane: "workspace-shared",
    resource: { class: "high", minimumCpuMillicores: 500, minimumMemoryMiB: 768, includedStorageGb: 12, recommendedWorkerConcurrency: 3 },
    aiNativeQualities: ["Attendee updates remain cited proposals", "Commit-time inventory checks", "Payment and gate receipts never inferred by a model"],
  },
  {
    id: "people",
    name: "PeopleWeave",
    category: "People operations",
    originalProductThesis: "Connect policies, onboarding, leave, attendance, reviews, and offboarding without delegating employment decisions to a model.",
    minPlan: "scale",
    minimumMonthlyPlanUsd: 50,
    dataPlane: "workspace-shared",
    resource: { class: "high", minimumCpuMillicores: 500, minimumMemoryMiB: 768, includedStorageGb: 10, recommendedWorkerConcurrency: 2 },
    aiNativeQualities: ["Evidence-cited growth proposals", "Human employment decisions", "Immutable policy and attendance correction receipts"],
  },
  {
    id: "metering",
    name: "MeterProof",
    category: "Usage billing",
    originalProductThesis: "Make every usage event, aggregate, plan, charge preview, credit, invoice, and payment independently reproducible.",
    minPlan: "fleet",
    minimumMonthlyPlanUsd: 200,
    dataPlane: "workspace-shared",
    resource: { class: "accelerated", minimumCpuMillicores: 1_500, minimumMemoryMiB: 2_048, includedStorageGb: 50, recommendedWorkerConcurrency: 8 },
    aiNativeQualities: ["Deterministic charge previews", "Invoice explanations cite frozen evidence", "No model-created charges or credits"],
  },
  {
    id: "assurance",
    name: "AssureGraph",
    category: "Risk and assurance",
    originalProductThesis: "Bind risks, controls, evidence, tests, remediations, exceptions, and audit packs to exact owners and clocks.",
    minPlan: "fleet",
    minimumMonthlyPlanUsd: 200,
    dataPlane: "workspace-shared",
    resource: { class: "high", minimumCpuMillicores: 900, minimumMemoryMiB: 1_536, includedStorageGb: 40, recommendedWorkerConcurrency: 4 },
    aiNativeQualities: ["Gap analysis remains a cited proposal", "Human control-test outcomes", "Content-addressed audit packs"],
  },
  {
    id: "live",
    name: "LiveForum",
    category: "Live sessions",
    originalProductThesis: "Coordinate grants, consent, broadcasts, chat, prompts, responses, and replay proposals without silent access or moderation.",
    minPlan: "fleet",
    minimumMonthlyPlanUsd: 200,
    dataPlane: "workspace-shared",
    resource: { class: "accelerated", minimumCpuMillicores: 2_000, minimumMemoryMiB: 3_072, includedStorageGb: 100, recommendedWorkerConcurrency: 12 },
    aiNativeQualities: ["Consent-pinned broadcast state", "Attributed moderation decisions", "Replay highlights remain unpublished proposals"],
  },
] as const satisfies readonly AdditiveWaveTwoModuleDefinition[];

const uuid = (description: string) => ({ type: "string", format: "uuid", description });
const text = (description: string, maxLength = 4_000) => ({ type: "string", minLength: 1, maxLength, description });
const optionalText = (description: string, maxLength = 4_000) => ({ type: "string", maxLength, description });
const integer = (description: string, minimum = 0, maximum = Number.MAX_SAFE_INTEGER) => ({ type: "integer", minimum, maximum, description });
const number = (description: string, minimum = -Number.MAX_VALUE, maximum = Number.MAX_VALUE) => ({ type: "number", minimum, maximum, description });
const boolean = (description: string) => ({ type: "boolean", description });
const dateTime = (description: string) => ({ type: "string", format: "date-time", description });
const date = (description: string) => ({ type: "string", pattern: "^\\d{4}-\\d{2}-\\d{2}$", description });
const sha256 = (description: string) => ({ type: "string", pattern: "^[a-f0-9]{64}$", description });
const enumString = (description: string, values: readonly string[]) => ({ type: "string", enum: values, description });
const strictObject = (description: string, required: readonly string[], properties: Record<string, Record<string, unknown>>) => ({ type: "object", description, required, properties, additionalProperties: false });
const array = (description: string, items: Record<string, unknown>, maxItems = 200, minItems = 0) => ({ type: "array", items, minItems, maxItems, description });
const stringArray = (description: string, maxItems = 100) => array(description, text("Value.", 500), maxItems);
const evidenceIds = array("Tenant-owned record IDs selected as evidence.", uuid("Evidence record ID."), 500, 1);
const modelId = text("Optional expected workspace-configured model identifier. When omitted, the trusted workspace policy is used; never a credential.", 200);
const externalEvidenceToken = optionalText("Short-lived hosting-layer attestation token for the exact external evidence. Required only when applying the effect, never for dry-run preview.", 4_096);
const idempotencyKey = { type: "string", pattern: "^[A-Za-z0-9._:-]{16,200}$", description: "A retry-safe key unique to this logical mutation." };
const approval = strictObject("Attributed human approval of the exact requested effect.", ["approved", "approvedBy", "approvedAt", "decisionId", "reason"], {
  approved: { const: true },
  approvedBy: text("Approving workspace identity.", 200),
  approvedAt: dateTime("Approval clock."),
  decisionId: { type: "string", pattern: "^[A-Za-z0-9._:-]{16,200}$" },
  reason: text("Reason grounded in reviewed evidence.", 1_000),
});

type Draft = Omit<AdditiveWaveTwoActionDefinition, "inputSchema" | "exampleInput" | "cliExample" | "mcpToolName" | "idempotent" | "requiredScope" | "minimumRole" | "risk" | "destructive" | "externalEffect" | "requiresApproval" | "supportsDryRun" | "effectBoundary" | "promptId" | "promptVersion"> & {
  required: readonly string[];
  properties: Record<string, Record<string, unknown>>;
  example: Record<string, unknown>;
  requiredScope?: AdditiveWaveTwoScope;
  minimumRole?: AdditiveWaveTwoRole;
  risk?: AdditiveWaveTwoRisk;
  destructive?: boolean;
  externalEffect?: AdditiveWaveTwoExternalEffect;
  requiresApproval?: boolean;
  supportsDryRun?: boolean;
};

function define(draft: Draft): AdditiveWaveTwoActionDefinition {
  const {
    required,
    properties: draftProperties,
    example,
    requiredScope,
    minimumRole,
    risk,
    destructive = false,
    externalEffect = draft.operation === "ai" ? "model" : "none",
    requiresApproval = destructive || (draft.operation === "mutation" && !["none", "model"].includes(externalEffect)),
    supportsDryRun = requiresApproval,
    ...base
  } = draft;
  const idempotent = draft.operation !== "read";
  const properties = { ...draftProperties };
  const requiredFields = [...required];
  const exampleInput = { ...example };
  if (idempotent) {
    properties.idempotencyKey = idempotencyKey;
    requiredFields.push("idempotencyKey");
    exampleInput.idempotencyKey = `${draft.moduleId}.${draft.id}.example-0001`;
  }
  if (supportsDryRun) {
    properties.dryRun = boolean("Validate and preview the exact effect without changing domain state.");
    properties.approval = approval;
    requiredFields.push("dryRun");
    exampleInput.dryRun = true;
  }
  const promptId = draft.operation === "ai" ? `${draft.moduleId}.${draft.id}` : undefined;
  const promptVersion = draft.operation === "ai" ? "2026-08-24.1" : undefined;
  const mcpToolName = `${draft.moduleId}_${draft.id.replaceAll("-", "_")}`;
  const cliInput = JSON.stringify(exampleInput).replaceAll("'", "'\\''");
  return {
    ...base,
    requiredScope: requiredScope ?? (draft.operation === "read" ? "read" : draft.operation === "ai" ? "ai" : "write"),
    minimumRole: minimumRole ?? (requiresApproval ? "admin" : draft.operation === "read" ? "viewer" : "member"),
    risk: risk ?? (destructive ? "critical" : requiresApproval ? "high" : draft.operation === "ai" ? "medium" : "low"),
    destructive,
    externalEffect,
    requiresApproval,
    supportsDryRun,
    idempotent,
    effectBoundary: draft.operation === "read" ? "read-only" : draft.operation === "ai" ? "proposal-only" : requiresApproval ? "approved-ledger-command" : "tenant-record",
    inputSchema: { type: "object", required: [...new Set(requiredFields)], properties, additionalProperties: false },
    exampleInput,
    cliExample: `supersuite action ${draft.moduleId} ${draft.id} '${cliInput}'`,
    mcpToolName,
    promptId,
    promptVersion,
  };
}

const sample = {
  record: "00000000-0000-4000-8000-000000000100",
  evidence: "00000000-0000-4000-8000-000000000101",
  actor: "workspace-user-0001",
};

const events = [
  define({ moduleId: "events", productName: "GatherLedger", id: "create-draft", title: "Create event draft", description: "Create a bounded event draft with UTC clocks, capacity, venue mode, and release purpose.", operation: "mutation", recordType: "event", required: ["key", "title", "purpose", "startsAt", "endsAt", "timeZone", "venueMode", "capacity"], properties: { key: text("Stable lowercase event key.", 80), title: text("Event title.", 240), purpose: text("Event purpose.", 2_000), startsAt: dateTime("UTC start."), endsAt: dateTime("UTC end."), timeZone: text("IANA display time zone.", 100), venueMode: enumString("Venue mode.", ["online", "physical", "hybrid"]), venue: optionalText("Venue description without access secrets.", 1_000), capacity: integer("Maximum issued tickets.", 1, 1_000_000) }, example: { key: "launch-day", title: "Launch day", purpose: "Customer education", startsAt: "2026-09-01T14:00:00.000Z", endsAt: "2026-09-01T17:00:00.000Z", timeZone: "America/New_York", venueMode: "hybrid", venue: "Main hall and hosted stream", capacity: 500 } }),
  define({ moduleId: "events", productName: "GatherLedger", id: "publish-release", title: "Publish approved event release", description: "Publish an exact event snapshot after human approval; the engine records a publication command and never calls a provider.", operation: "mutation", recordType: "event-release", externalEffect: "publication", required: ["eventId", "expectedVersion", "releaseHash"], properties: { eventId: uuid("Event ID."), expectedVersion: integer("Current event version.", 1), releaseHash: sha256("Hash returned by the deterministic release preview.") }, example: { eventId: sample.record, expectedVersion: 1, releaseHash: "a".repeat(64) } }),
  define({ moduleId: "events", productName: "GatherLedger", id: "define-ticket-type", title: "Define ticket inventory", description: "Define price, currency, quantity, and sales clocks against one event without opening sales.", operation: "mutation", recordType: "ticket-type", required: ["eventId", "key", "name", "priceMinor", "currency", "quantity", "salesStartAt", "salesEndAt"], properties: { eventId: uuid("Event ID."), key: text("Stable ticket key.", 80), name: text("Ticket name.", 160), priceMinor: integer("Price in minor currency units.", 0, 1_000_000_000), currency: { type: "string", pattern: "^[A-Z]{3}$" }, quantity: integer("Available quantity.", 1, 1_000_000), salesStartAt: dateTime("UTC sales start."), salesEndAt: dateTime("UTC sales end.") }, example: { eventId: sample.record, key: "general", name: "General admission", priceMinor: 2500, currency: "USD", quantity: 400, salesStartAt: "2026-08-25T00:00:00.000Z", salesEndAt: "2026-09-01T13:00:00.000Z" } }),
  define({ moduleId: "events", productName: "GatherLedger", id: "reserve-tickets", title: "Reserve available tickets", description: "Create an expiring inventory hold after checking committed reservations and issued tickets in the tenant ledger.", operation: "mutation", recordType: "ticket-reservation", required: ["ticketTypeId", "customerRef", "quantity", "expiresAt"], properties: { ticketTypeId: uuid("Ticket type ID."), customerRef: text("Pseudonymous customer reference.", 200), quantity: integer("Tickets to hold.", 1, 100), expiresAt: dateTime("UTC hold expiry.") }, example: { ticketTypeId: sample.record, customerRef: "customer-42", quantity: 2, expiresAt: "2026-08-24T18:00:00.000Z" } }),
  define({ moduleId: "events", productName: "GatherLedger", id: "create-checkout", title: "Approve checkout command", description: "Freeze the exact reservation total as an approved payment-provider command; provider execution stays outside this engine.", operation: "mutation", recordType: "checkout-command", externalEffect: "financial", required: ["reservationId", "expectedAmountMinor", "currency", "returnUrl"], properties: { reservationId: uuid("Reservation ID."), expectedAmountMinor: integer("Expected total in minor units.", 0, 100_000_000_000), currency: { type: "string", pattern: "^[A-Z]{3}$" }, returnUrl: { type: "string", format: "uri", pattern: "^https://" } }, example: { reservationId: sample.record, expectedAmountMinor: 5000, currency: "USD", returnUrl: "https://events.example.test/complete" } }),
  define({ moduleId: "events", productName: "GatherLedger", id: "record-payment", title: "Record verified ticket payment", description: "Record a provider-verifiable receipt for the exact checkout total; this action never initiates or fabricates payment.", operation: "mutation", recordType: "payment-receipt", externalEffect: "financial", required: ["checkoutId", "provider", "providerReceiptId", "amountMinor", "currency", "paidAt"], properties: { checkoutId: uuid("Checkout command ID."), provider: text("Payment provider name.", 80), providerReceiptId: text("Immutable provider receipt ID.", 240), amountMinor: integer("Paid amount in minor units.", 0, 100_000_000_000), currency: { type: "string", pattern: "^[A-Z]{3}$" }, paidAt: dateTime("Provider payment clock."), externalEvidenceToken }, example: { checkoutId: sample.record, provider: "payment-provider", providerReceiptId: "receipt-42", amountMinor: 5000, currency: "USD", paidAt: "2026-08-24T17:00:00.000Z" } }),
  define({ moduleId: "events", productName: "GatherLedger", id: "issue-ticket", title: "Issue approved access ticket", description: "Issue one ticket against paid reserved inventory after an attributed access approval.", operation: "mutation", recordType: "ticket", externalEffect: "access", required: ["paymentReceiptId", "reservationId", "attendeeRef", "ordinal"], properties: { paymentReceiptId: uuid("Payment receipt ID."), reservationId: uuid("Reservation ID."), attendeeRef: text("Pseudonymous attendee reference.", 200), ordinal: integer("One-based ticket ordinal within the reservation.", 1, 100) }, example: { paymentReceiptId: sample.evidence, reservationId: sample.record, attendeeRef: "attendee-42", ordinal: 1 } }),
  define({ moduleId: "events", productName: "GatherLedger", id: "request-refund", title: "Request ticket refund", description: "Create a reasoned refund request without changing money, access, or ticket state.", operation: "mutation", recordType: "refund-request", required: ["ticketId", "reason", "requestedAmountMinor"], properties: { ticketId: uuid("Ticket ID."), reason: text("Refund reason.", 2_000), requestedAmountMinor: integer("Requested refund in minor units.", 0, 100_000_000_000) }, example: { ticketId: sample.record, reason: "Unable to attend", requestedAmountMinor: 2500 } }),
  define({ moduleId: "events", productName: "GatherLedger", id: "record-refund", title: "Record verified refund", description: "Record an externally verified refund receipt and revoke the exact ticket after human approval.", operation: "mutation", recordType: "refund-receipt", destructive: true, externalEffect: "financial", required: ["refundRequestId", "provider", "providerReceiptId", "amountMinor", "currency", "refundedAt"], properties: { refundRequestId: uuid("Refund request ID."), provider: text("Payment provider name.", 80), providerReceiptId: text("Immutable refund receipt ID.", 240), amountMinor: integer("Refunded amount in minor units.", 0, 100_000_000_000), currency: { type: "string", pattern: "^[A-Z]{3}$" }, refundedAt: dateTime("Provider refund clock."), externalEvidenceToken }, example: { refundRequestId: sample.record, provider: "payment-provider", providerReceiptId: "refund-42", amountMinor: 2500, currency: "USD", refundedAt: "2026-08-25T17:00:00.000Z" } }),
  define({ moduleId: "events", productName: "GatherLedger", id: "check-in", title: "Record approved venue access", description: "Consume one issued ticket at a named gate and persist the attributed access receipt.", operation: "mutation", recordType: "check-in-receipt", externalEffect: "access", required: ["ticketId", "gate", "checkedInAt", "scannerReceiptId"], properties: { ticketId: uuid("Ticket ID."), gate: text("Gate or virtual room.", 160), checkedInAt: dateTime("Access clock."), scannerReceiptId: text("Immutable scanner or host receipt.", 240), externalEvidenceToken }, example: { ticketId: sample.record, gate: "Main entrance", checkedInAt: "2026-09-01T13:45:00.000Z", scannerReceiptId: "scan-42" } }),
  define({ moduleId: "events", productName: "GatherLedger", id: "propose-attendee-update", title: "Queue attendee update proposal", description: "Queue cited attendee copy; it cannot publish, message, refund, issue, or check in a ticket.", operation: "ai", recordType: "ai-proposal-request", required: ["eventId", "audience", "goal", "evidenceIds"], properties: { eventId: uuid("Event ID."), audience: text("Intended audience.", 1_000), goal: text("Update goal.", 2_000), evidenceIds, modelId }, example: { eventId: sample.record, audience: "Registered attendees", goal: "Propose a factual arrival update.", evidenceIds: [sample.evidence] } }),
  define({ moduleId: "events", productName: "GatherLedger", id: "summarize", title: "Queue cited event summary", description: "Queue a fact-versus-hypothesis event summary pinned to selected tenant evidence and clocks.", operation: "ai", recordType: "ai-proposal-request", required: ["eventId", "question", "evidenceIds"], properties: { eventId: uuid("Event ID."), question: text("Summary question.", 2_000), evidenceIds, modelId }, example: { eventId: sample.record, question: "Summarize sales, attendance, and unresolved issues.", evidenceIds: [sample.evidence] } }),
];

const people = [
  define({ moduleId: "people", productName: "PeopleWeave", id: "create-profile", title: "Create purpose-bound people profile", description: "Create a minimum-data profile bound to one authenticated workspace member, manager, dates, and privacy class.", operation: "mutation", recordType: "people-profile", minimumRole: "admin", required: ["employeeRef", "displayName", "employmentType", "startDate", "managerRef", "privacy"], properties: { employeeRef: text("Exact workspace user ID of the person represented by this profile.", 200), displayName: text("Display name.", 160), employmentType: enumString("Employment relationship.", ["employee", "contractor", "intern", "temporary"]), startDate: date("Employment start date."), managerRef: text("Manager workspace reference.", 200), privacy: enumString("Profile privacy class.", ["restricted", "people-team", "manager-and-person"]) }, example: { employeeRef: sample.actor, displayName: "Avery", employmentType: "employee", startDate: "2026-09-01", managerRef: sample.actor, privacy: "people-team" } }),
  define({ moduleId: "people", productName: "PeopleWeave", id: "start-onboarding", title: "Start approved onboarding", description: "Start a human-approved onboarding checklist for an existing profile without making an employment decision.", operation: "mutation", recordType: "onboarding", externalEffect: "employment", required: ["profileId", "ownerRef", "dueAt", "checklist"], properties: { profileId: uuid("People profile ID."), ownerRef: text("Onboarding owner.", 200), dueAt: dateTime("UTC completion target."), checklist: array("Bounded checklist items.", strictObject("Checklist item.", ["key", "title"], { key: text("Stable item key.", 80), title: text("Item title.", 500) }), 100, 1) }, example: { profileId: sample.record, ownerRef: sample.actor, dueAt: "2026-09-05T17:00:00.000Z", checklist: [{ key: "security", title: "Complete security briefing" }] } }),
  define({ moduleId: "people", productName: "PeopleWeave", id: "publish-policy", title: "Publish approved people policy", description: "Publish an exact content-addressed policy revision after attributed human approval.", operation: "mutation", recordType: "people-policy", externalEffect: "publication", required: ["key", "title", "content", "contentHash", "effectiveAt", "audience"], properties: { key: text("Stable policy key.", 80), title: text("Policy title.", 240), content: text("Human-authored policy.", 100_000), contentHash: sha256("SHA-256 of exact policy content."), effectiveAt: dateTime("UTC effective clock."), audience: text("Policy audience.", 1_000) }, example: { key: "remote-work", title: "Remote work", content: "Approved policy text", contentHash: "a".repeat(64), effectiveAt: "2026-09-01T00:00:00.000Z", audience: "All team members" } }),
  define({ moduleId: "people", productName: "PeopleWeave", id: "acknowledge-policy", title: "Record policy acknowledgement", description: "Bind a subject-provided acknowledgement receipt to the exact published policy hash.", operation: "mutation", recordType: "policy-acknowledgement", externalEffect: "consent", requiresApproval: false, supportsDryRun: false, required: ["policyId", "profileId", "contentHash", "acknowledgedAt", "subjectReceiptId"], properties: { policyId: uuid("Published policy ID."), profileId: uuid("People profile ID."), contentHash: sha256("Exact acknowledged policy hash."), acknowledgedAt: dateTime("Subject acknowledgement clock."), subjectReceiptId: text("Immutable subject interaction receipt.", 240) }, example: { policyId: sample.record, profileId: sample.evidence, contentHash: "a".repeat(64), acknowledgedAt: "2026-09-02T14:00:00.000Z", subjectReceiptId: "ack-42" } }),
  define({ moduleId: "people", productName: "PeopleWeave", id: "request-leave", title: "Request leave", description: "Create a private leave request without approving, denying, scoring, or inferring eligibility.", operation: "mutation", recordType: "leave-request", required: ["profileId", "leaveKind", "startsOn", "endsOn", "subjectReceiptId"], properties: { profileId: uuid("People profile ID."), leaveKind: enumString("Leave category.", ["vacation", "sick", "caregiving", "personal", "other"]), startsOn: date("First requested date."), endsOn: date("Last requested date."), note: optionalText("Optional subject-provided note.", 2_000), subjectReceiptId: text("Immutable subject request receipt.", 240) }, example: { profileId: sample.record, leaveKind: "vacation", startsOn: "2026-09-10", endsOn: "2026-09-12", note: "Planned time away", subjectReceiptId: "leave-request-42" } }),
  define({ moduleId: "people", productName: "PeopleWeave", id: "decide-leave", title: "Record human leave decision", description: "Record an approved or denied leave decision with an attributed employment-decision receipt.", operation: "mutation", recordType: "leave-decision", externalEffect: "employment", required: ["requestId", "decision", "rationale", "decisionReceiptId"], properties: { requestId: uuid("Leave request ID."), decision: enumString("Human decision.", ["approved", "denied"]), rationale: text("Decision rationale.", 2_000), decisionReceiptId: text("Immutable HR decision receipt.", 240) }, example: { requestId: sample.record, decision: "approved", rationale: "Coverage confirmed", decisionReceiptId: "leave-decision-42" } }),
  define({ moduleId: "people", productName: "PeopleWeave", id: "record-attendance", title: "Record attendance interval", description: "Append an exact attendance interval with subject and source provenance.", operation: "mutation", recordType: "attendance", required: ["profileId", "clockInAt", "clockOutAt", "source", "sourceReceiptId"], properties: { profileId: uuid("People profile ID."), clockInAt: dateTime("UTC clock-in."), clockOutAt: dateTime("UTC clock-out."), source: enumString("Attendance source.", ["subject-entry", "approved-import", "time-clock"]), sourceReceiptId: text("Immutable source receipt.", 240) }, example: { profileId: sample.record, clockInAt: "2026-09-01T13:00:00.000Z", clockOutAt: "2026-09-01T21:00:00.000Z", source: "subject-entry", sourceReceiptId: "attendance-42" } }),
  define({ moduleId: "people", productName: "PeopleWeave", id: "correct-attendance", title: "Correct attendance with audit", description: "Supersede an attendance interval after explicit approval while preserving its original clocks and source.", operation: "mutation", recordType: "attendance-correction", destructive: true, externalEffect: "employment", required: ["attendanceId", "expectedVersion", "clockInAt", "clockOutAt", "reason", "correctionReceiptId"], properties: { attendanceId: uuid("Attendance record ID."), expectedVersion: integer("Current attendance version.", 1), clockInAt: dateTime("Corrected UTC clock-in."), clockOutAt: dateTime("Corrected UTC clock-out."), reason: text("Correction reason.", 2_000), correctionReceiptId: text("Immutable correction receipt.", 240) }, example: { attendanceId: sample.record, expectedVersion: 1, clockInAt: "2026-09-01T13:05:00.000Z", clockOutAt: "2026-09-01T21:00:00.000Z", reason: "Subject-confirmed clock correction", correctionReceiptId: "correction-42" } }),
  define({ moduleId: "people", productName: "PeopleWeave", id: "open-review", title: "Open structured review", description: "Open a purpose-bound review with a human-authored rubric and named authenticated reviewer.", operation: "mutation", recordType: "people-review", minimumRole: "admin", required: ["profileId", "cycleKey", "reviewerRef", "dueAt", "rubric"], properties: { profileId: uuid("People profile ID."), cycleKey: text("Stable review cycle key.", 80), reviewerRef: text("Exact authenticated reviewer workspace user ID.", 200), dueAt: dateTime("UTC due clock."), rubric: array("Human-authored review criteria.", strictObject("Review criterion.", ["key", "question"], { key: text("Criterion key.", 80), question: text("Criterion question.", 1_000) }), 100, 1) }, example: { profileId: sample.record, cycleKey: "2026-h2", reviewerRef: sample.actor, dueAt: "2026-12-01T17:00:00.000Z", rubric: [{ key: "delivery", question: "What outcomes are supported by evidence?" }] } }),
  define({ moduleId: "people", productName: "PeopleWeave", id: "submit-review", title: "Submit human review", description: "Submit human-authored responses and selected evidence; the system does not generate ratings or employment decisions.", operation: "mutation", recordType: "review-submission", required: ["reviewId", "submittedBy", "responses", "evidenceIds", "submissionReceiptId"], properties: { reviewId: uuid("Review ID."), submittedBy: text("Submitting workspace identity.", 200), responses: array("Criterion responses.", strictObject("Review response.", ["criterionKey", "response"], { criterionKey: text("Criterion key.", 80), response: text("Human-authored response.", 10_000) }), 100, 1), evidenceIds, submissionReceiptId: text("Immutable submission receipt.", 240) }, example: { reviewId: sample.record, submittedBy: sample.actor, responses: [{ criterionKey: "delivery", response: "Shipped the approved release." }], evidenceIds: [sample.evidence], submissionReceiptId: "review-42" } }),
  define({ moduleId: "people", productName: "PeopleWeave", id: "propose-growth-plan", title: "Queue cited growth-plan proposal", description: "Queue evidence-cited development ideas; it cannot score a person, change employment, or assign required work.", operation: "ai", recordType: "ai-proposal-request", required: ["profileId", "goal", "evidenceIds"], properties: { profileId: uuid("People profile ID."), goal: text("Development objective.", 2_000), evidenceIds, modelId }, example: { profileId: sample.record, goal: "Propose optional learning opportunities grounded in submitted evidence.", evidenceIds: [sample.evidence] } }),
  define({ moduleId: "people", productName: "PeopleWeave", id: "record-access-revocation", title: "Record verified access revocation", description: "Bind one system account revocation to the exact profile, source receipt, operator approval, and revocation clock before offboarding can close the profile.", operation: "mutation", recordType: "access-revocation-receipt", externalEffect: "access", required: ["profileId", "system", "accountRef", "sourceReceiptId", "revokedAt"], properties: { profileId: uuid("People profile ID."), system: text("System whose access was revoked.", 160), accountRef: text("Pseudonymous account reference in that system.", 240), sourceReceiptId: text("Immutable receipt from the source system or approved operator workflow.", 240), revokedAt: dateTime("Verified revocation clock."), externalEvidenceToken }, example: { profileId: sample.record, system: "identity-provider", accountRef: sample.actor, sourceReceiptId: "identity-revocation-42", revokedAt: "2026-09-30T20:45:00.000Z" } }),
  define({ moduleId: "people", productName: "PeopleWeave", id: "offboard", title: "Record approved offboarding", description: "Close a profile only when the current owner's human approval decision ID matches the employment receipt and every selected tenant access-revocation receipt resolves to that exact profile.", operation: "mutation", recordType: "offboarding-receipt", destructive: true, externalEffect: "employment", minimumRole: "owner", required: ["profileId", "effectiveAt", "reason", "employmentDecisionReceiptId", "accessRevocationReceiptIds"], properties: { profileId: uuid("People profile ID."), effectiveAt: dateTime("UTC offboarding clock."), reason: text("Human decision rationale.", 2_000), employmentDecisionReceiptId: text("Exact decisionId from the attributable human approval envelope.", 200), accessRevocationReceiptIds: array("Tenant access-revocation receipt record IDs.", uuid("Access-revocation receipt record ID."), 100, 1) }, example: { profileId: sample.record, effectiveAt: "2026-09-30T21:00:00.000Z", reason: "Approved contract completion", employmentDecisionReceiptId: "offboarding.approval.0001", accessRevocationReceiptIds: [sample.evidence] } }),
];

const metering = [
  define({ moduleId: "metering", productName: "MeterProof", id: "create-meter", title: "Create typed usage meter", description: "Create a stable meter with unit, aggregation, event key, and allowlisted dimensions.", operation: "mutation", recordType: "usage-meter", required: ["key", "name", "unit", "aggregation", "eventKey", "dimensionKeys"], properties: { key: text("Stable meter key.", 80), name: text("Meter name.", 160), unit: text("Measured unit.", 80), aggregation: enumString("Aggregation rule.", ["sum", "count", "maximum", "last"]), eventKey: text("Expected event type.", 120), dimensionKeys: stringArray("Allowlisted dimension keys.", 50) }, example: { key: "api-calls", name: "API calls", unit: "request", aggregation: "sum", eventKey: "api.request.completed", dimensionKeys: ["region"] } }),
  define({ moduleId: "metering", productName: "MeterProof", id: "ingest-event", title: "Ingest deduplicated usage event", description: "Append one source-attested usage event under the meter schema without accepting executable expressions.", operation: "mutation", recordType: "usage-event", required: ["meterId", "sourceEventId", "subjectRef", "quantity", "occurredAt", "dimensions", "sourceAttestation"], properties: { meterId: uuid("Usage meter ID."), sourceEventId: text("Globally stable source event ID.", 240), subjectRef: text("Billed subject reference.", 200), quantity: number("Measured quantity.", 0, 1_000_000_000_000), occurredAt: dateTime("Source occurrence clock."), dimensions: { type: "object", description: "Allowlisted scalar dimensions." }, sourceAttestation: text("Source revision, signature receipt, or import hash.", 500), externalEvidenceToken }, example: { meterId: sample.record, sourceEventId: "usage-42", subjectRef: "customer-42", quantity: 3, occurredAt: "2026-08-24T16:00:00.000Z", dimensions: { region: "us-east" }, sourceAttestation: "signed-batch-42" } }),
  define({ moduleId: "metering", productName: "MeterProof", id: "aggregate-usage", title: "Freeze usage aggregate", description: "Aggregate exact tenant events for one meter, subject, and half-open UTC period, then freeze their IDs and hash.", operation: "mutation", recordType: "usage-aggregate", required: ["meterId", "subjectRef", "periodStart", "periodEnd"], properties: { meterId: uuid("Usage meter ID."), subjectRef: text("Billed subject reference.", 200), periodStart: dateTime("Inclusive UTC period start."), periodEnd: dateTime("Exclusive UTC period end.") }, example: { meterId: sample.record, subjectRef: "customer-42", periodStart: "2026-08-01T00:00:00.000Z", periodEnd: "2026-09-01T00:00:00.000Z" } }),
  define({ moduleId: "metering", productName: "MeterProof", id: "propose-plan", title: "Queue pricing-plan proposal", description: "Queue a cited pricing hypothesis; it cannot publish prices, subscribe a customer, grant credit, or create an invoice.", operation: "ai", recordType: "ai-proposal-request", required: ["goal", "currency", "evidenceIds"], properties: { goal: text("Pricing objective.", 2_000), currency: { type: "string", pattern: "^[A-Z]{3}$" }, evidenceIds, modelId }, example: { goal: "Propose a transparent plan grounded in observed usage.", currency: "USD", evidenceIds: [sample.evidence] } }),
  define({ moduleId: "metering", productName: "MeterProof", id: "publish-plan", title: "Publish approved billing plan", description: "Publish exact human-approved base and per-unit pricing with a content hash.", operation: "mutation", recordType: "billing-plan", externalEffect: "financial", required: ["key", "name", "currency", "interval", "meterId", "baseFeeMinor", "unitPriceMinor", "contentHash"], properties: { key: text("Stable plan key.", 80), name: text("Plan name.", 160), currency: { type: "string", pattern: "^[A-Z]{3}$" }, interval: enumString("Billing interval.", ["monthly", "annual"]), meterId: uuid("Usage meter ID."), baseFeeMinor: integer("Recurring base fee in minor units.", 0, 100_000_000_000), unitPriceMinor: integer("Per-unit price in minor units.", 0, 100_000_000_000), contentHash: sha256("Hash of exact plan terms.") }, example: { key: "growth", name: "Growth", currency: "USD", interval: "monthly", meterId: sample.record, baseFeeMinor: 700, unitPriceMinor: 2, contentHash: "b".repeat(64) } }),
  define({ moduleId: "metering", productName: "MeterProof", id: "preview-charge", title: "Preview deterministic charge", description: "Compute a charge from one published plan and frozen aggregates without persisting or calling a provider.", operation: "read", recordType: "charge-preview", required: ["planId", "aggregateIds"], properties: { planId: uuid("Published billing plan ID."), aggregateIds: array("Frozen usage aggregate IDs.", uuid("Aggregate ID."), 500, 1) }, example: { planId: sample.record, aggregateIds: [sample.evidence] } }),
  define({ moduleId: "metering", productName: "MeterProof", id: "create-subscription", title: "Create approved subscription", description: "Bind a subject to exact published plan terms after attributed approval; no provider call occurs here.", operation: "mutation", recordType: "billing-subscription", externalEffect: "financial", required: ["planId", "subjectRef", "startsAt", "billingAnchorDay", "agreementReceiptId"], properties: { planId: uuid("Published plan ID."), subjectRef: text("Billed subject reference.", 200), startsAt: dateTime("UTC subscription start."), billingAnchorDay: integer("Monthly billing anchor day.", 1, 28), agreementReceiptId: text("Immutable customer agreement receipt.", 240) }, example: { planId: sample.record, subjectRef: "customer-42", startsAt: "2026-09-01T00:00:00.000Z", billingAnchorDay: 1, agreementReceiptId: "agreement-42" } }),
  define({ moduleId: "metering", productName: "MeterProof", id: "grant-credit", title: "Grant approved account credit", description: "Append a bounded credit grant after human approval without changing historical invoice totals.", operation: "mutation", recordType: "credit-grant", externalEffect: "financial", required: ["subscriptionId", "amountMinor", "currency", "reason", "creditReceiptId"], properties: { subscriptionId: uuid("Subscription ID."), amountMinor: integer("Credit amount in minor units.", 1, 100_000_000_000), currency: { type: "string", pattern: "^[A-Z]{3}$" }, reason: text("Credit reason.", 2_000), creditReceiptId: text("Immutable business approval receipt.", 240) }, example: { subscriptionId: sample.record, amountMinor: 500, currency: "USD", reason: "Approved service credit", creditReceiptId: "credit-42" } }),
  define({ moduleId: "metering", productName: "MeterProof", id: "draft-invoice", title: "Draft reproducible invoice", description: "Create an invoice draft from exact aggregates, plan terms, and unused credit grants.", operation: "mutation", recordType: "billing-invoice", required: ["subscriptionId", "periodStart", "periodEnd", "aggregateIds"], properties: { subscriptionId: uuid("Subscription ID."), periodStart: dateTime("Inclusive UTC period start."), periodEnd: dateTime("Exclusive UTC period end."), aggregateIds: array("Frozen usage aggregate IDs.", uuid("Aggregate ID."), 500, 1) }, example: { subscriptionId: sample.record, periodStart: "2026-08-01T00:00:00.000Z", periodEnd: "2026-09-01T00:00:00.000Z", aggregateIds: [sample.evidence] } }),
  define({ moduleId: "metering", productName: "MeterProof", id: "finalize-invoice", title: "Finalize approved invoice", description: "Freeze exact invoice totals and evidence after human approval; delivery and collection remain separate.", operation: "mutation", recordType: "billing-invoice", externalEffect: "financial", required: ["invoiceId", "expectedVersion", "totalsHash"], properties: { invoiceId: uuid("Draft invoice ID."), expectedVersion: integer("Current invoice version.", 1), totalsHash: sha256("Hash of exact totals and evidence IDs.") }, example: { invoiceId: sample.record, expectedVersion: 1, totalsHash: "c".repeat(64) } }),
  define({ moduleId: "metering", productName: "MeterProof", id: "record-payment", title: "Record verified invoice payment", description: "Append a provider-verifiable invoice payment receipt; this action never initiates or fabricates payment.", operation: "mutation", recordType: "invoice-payment-receipt", externalEffect: "financial", required: ["invoiceId", "provider", "providerReceiptId", "amountMinor", "currency", "paidAt"], properties: { invoiceId: uuid("Final invoice ID."), provider: text("Payment provider name.", 80), providerReceiptId: text("Immutable provider receipt ID.", 240), amountMinor: integer("Paid amount in minor units.", 0, 100_000_000_000), currency: { type: "string", pattern: "^[A-Z]{3}$" }, paidAt: dateTime("Provider payment clock."), externalEvidenceToken }, example: { invoiceId: sample.record, provider: "payment-provider", providerReceiptId: "invoice-payment-42", amountMinor: 1200, currency: "USD", paidAt: "2026-09-02T12:00:00.000Z" } }),
  define({ moduleId: "metering", productName: "MeterProof", id: "explain-invoice", title: "Queue cited invoice explanation", description: "Queue a line-by-line explanation pinned to exact plan, aggregate, credit, and invoice records; it cannot change or send the invoice.", operation: "ai", recordType: "ai-proposal-request", required: ["invoiceId", "question", "evidenceIds"], properties: { invoiceId: uuid("Invoice ID."), question: text("Explanation question.", 2_000), evidenceIds, modelId }, example: { invoiceId: sample.record, question: "Explain each charge and credit in plain language.", evidenceIds: [sample.evidence] } }),
];

const assurance = [
  define({ moduleId: "assurance", productName: "AssureGraph", id: "create-program", title: "Create assurance program", description: "Create an assurance program with framework, owner, purpose, and explicit review period.", operation: "mutation", recordType: "assurance-program", required: ["key", "name", "framework", "purpose", "ownerRef", "periodStart", "periodEnd"], properties: { key: text("Stable program key.", 80), name: text("Program name.", 160), framework: text("Framework or internal standard.", 160), purpose: text("Program purpose.", 2_000), ownerRef: text("Accountable workspace identity.", 200), periodStart: date("Review period start."), periodEnd: date("Review period end.") }, example: { key: "security-2026", name: "Security assurance 2026", framework: "Internal security baseline", purpose: "Verify operating controls", ownerRef: sample.actor, periodStart: "2026-01-01", periodEnd: "2026-12-31" } }),
  define({ moduleId: "assurance", productName: "AssureGraph", id: "register-subject", title: "Register assurance subject", description: "Register an owned system, process, vendor, or data set with classification and provenance.", operation: "mutation", recordType: "assurance-subject", required: ["programId", "kind", "name", "ownerRef", "classification"], properties: { programId: uuid("Assurance program ID."), kind: enumString("Subject kind.", ["system", "process", "vendor", "dataset"]), name: text("Subject name.", 240), ownerRef: text("Subject owner.", 200), classification: enumString("Data or operational classification.", ["public", "internal", "confidential", "restricted"]) }, example: { programId: sample.record, kind: "system", name: "Customer portal", ownerRef: sample.actor, classification: "confidential" } }),
  define({ moduleId: "assurance", productName: "AssureGraph", id: "create-risk", title: "Create owned risk", description: "Create a human-authored risk statement with explicit likelihood, impact, subject, and owner.", operation: "mutation", recordType: "assurance-risk", required: ["programId", "subjectId", "statement", "likelihood", "impact", "ownerRef"], properties: { programId: uuid("Program ID."), subjectId: uuid("Assurance subject ID."), statement: text("Human-authored risk statement.", 4_000), likelihood: integer("Likelihood score from one to five.", 1, 5), impact: integer("Impact score from one to five.", 1, 5), ownerRef: text("Risk owner.", 200) }, example: { programId: sample.record, subjectId: sample.evidence, statement: "Unreviewed changes could weaken access controls.", likelihood: 2, impact: 5, ownerRef: sample.actor } }),
  define({ moduleId: "assurance", productName: "AssureGraph", id: "publish-control", title: "Publish approved control", description: "Publish an exact control objective and procedure after attributed approval and content hashing.", operation: "mutation", recordType: "assurance-control", externalEffect: "publication", required: ["programId", "key", "title", "objective", "procedure", "ownerRef", "contentHash"], properties: { programId: uuid("Program ID."), key: text("Stable control key.", 80), title: text("Control title.", 240), objective: text("Control objective.", 4_000), procedure: text("Human-authored operating procedure.", 20_000), ownerRef: text("Control owner.", 200), contentHash: sha256("Hash of exact objective and procedure.") }, example: { programId: sample.record, key: "access-review", title: "Quarterly access review", objective: "Remove unneeded access", procedure: "Review the approved identity export each quarter.", ownerRef: sample.actor, contentHash: "d".repeat(64) } }),
  define({ moduleId: "assurance", productName: "AssureGraph", id: "map-control", title: "Map control to risks", description: "Create an explicit many-to-many control mapping with human-authored rationale.", operation: "mutation", recordType: "control-risk-map", required: ["controlId", "riskIds", "rationale"], properties: { controlId: uuid("Published control ID."), riskIds: array("Mapped assurance risk IDs.", uuid("Risk ID."), 100, 1), rationale: text("Mapping rationale.", 4_000) }, example: { controlId: sample.record, riskIds: [sample.evidence], rationale: "The control reduces unreviewed access." } }),
  define({ moduleId: "assurance", productName: "AssureGraph", id: "request-evidence", title: "Request control evidence", description: "Create an attributed evidence request with owner, requirements, and due clock.", operation: "mutation", recordType: "evidence-request", required: ["controlId", "ownerRef", "requirements", "dueAt"], properties: { controlId: uuid("Control ID."), ownerRef: text("Evidence owner.", 200), requirements: text("Required evidence and period.", 4_000), dueAt: dateTime("UTC due clock.") }, example: { controlId: sample.record, ownerRef: sample.actor, requirements: "Approved access review export and sign-off", dueAt: "2026-10-01T17:00:00.000Z" } }),
  define({ moduleId: "assurance", productName: "AssureGraph", id: "attach-evidence", title: "Attach governed evidence reference", description: "Link a tenant-owned source record, immutable content hash, observation clock, and provenance without copying credentials or mutable URLs.", operation: "mutation", recordType: "assurance-evidence", required: ["requestId", "sourceRecordId", "contentHash", "observedAt", "provenance"], properties: { requestId: uuid("Evidence request ID."), sourceRecordId: uuid("Tenant-owned shared-database source record ID."), contentHash: sha256("Immutable evidence content hash."), observedAt: dateTime("Evidence observation clock."), provenance: text("Acquisition and custody notes.", 4_000) }, example: { requestId: sample.record, sourceRecordId: sample.evidence, contentHash: "e".repeat(64), observedAt: "2026-09-30T16:00:00.000Z", provenance: "Approved export registered by the control owner" } }),
  define({ moduleId: "assurance", productName: "AssureGraph", id: "test-control", title: "Record human control test", description: "Record an authenticated tester-authored outcome against exact evidence; a model cannot pass or fail the control.", operation: "mutation", recordType: "control-test", minimumRole: "admin", required: ["controlId", "testerRef", "outcome", "testedAt", "evidenceIds", "notes"], properties: { controlId: uuid("Control ID."), testerRef: text("Exact authenticated tester workspace user ID.", 200), outcome: enumString("Human test outcome.", ["effective", "partially-effective", "ineffective", "not-tested"]), testedAt: dateTime("UTC test clock."), evidenceIds, notes: text("Tester-authored notes.", 10_000) }, example: { controlId: sample.record, testerRef: sample.actor, outcome: "effective", testedAt: "2026-10-02T16:00:00.000Z", evidenceIds: [sample.evidence], notes: "All sampled removals had approvals." } }),
  define({ moduleId: "assurance", productName: "AssureGraph", id: "propose-gap", title: "Queue cited assurance-gap proposal", description: "Queue possible gaps with citations and uncertainty; it cannot change a risk, test result, remediation, or exception.", operation: "ai", recordType: "ai-proposal-request", required: ["programId", "question", "evidenceIds"], properties: { programId: uuid("Program ID."), question: text("Gap-analysis question.", 2_000), evidenceIds, modelId }, example: { programId: sample.record, question: "Which evidence-backed gaps need human review?", evidenceIds: [sample.evidence] } }),
  define({ moduleId: "assurance", productName: "AssureGraph", id: "approve-remediation", title: "Approve remediation plan", description: "Approve an owned remediation with due clock and exact evidence after human review.", operation: "mutation", recordType: "assurance-remediation", destructive: true, required: ["riskId", "plan", "ownerRef", "dueAt", "evidenceIds"], properties: { riskId: uuid("Risk ID."), plan: text("Human-approved remediation plan.", 10_000), ownerRef: text("Remediation owner.", 200), dueAt: dateTime("UTC due clock."), evidenceIds }, example: { riskId: sample.record, plan: "Add a second reviewer to privileged access changes.", ownerRef: sample.actor, dueAt: "2026-11-01T17:00:00.000Z", evidenceIds: [sample.evidence] } }),
  define({ moduleId: "assurance", productName: "AssureGraph", id: "record-exception", title: "Record approved control exception", description: "Record a bounded, expiring exception with compensating controls and attributed approval.", operation: "mutation", recordType: "control-exception", destructive: true, required: ["controlId", "reason", "expiresAt", "compensatingControls"], properties: { controlId: uuid("Control ID."), reason: text("Exception reason.", 4_000), expiresAt: dateTime("UTC exception expiry."), compensatingControls: stringArray("Human-approved compensating controls.", 100) }, example: { controlId: sample.record, reason: "Legacy migration window", expiresAt: "2026-10-31T23:59:59.000Z", compensatingControls: ["Daily owner review"] } }),
  define({ moduleId: "assurance", productName: "AssureGraph", id: "export-audit-pack", title: "Freeze private audit pack", description: "Create a private content-addressed manifest of selected tenant records and an as-of clock.", operation: "mutation", recordType: "audit-pack", required: ["programId", "asOf", "recordIds", "format"], properties: { programId: uuid("Program ID."), asOf: dateTime("Audit pack reporting clock."), recordIds: array("Selected tenant record IDs.", uuid("Record ID."), 5_000, 1), format: enumString("Manifest format.", ["canonical-json", "csv-index"]) }, example: { programId: sample.record, asOf: "2026-12-31T23:59:59.000Z", recordIds: [sample.evidence], format: "canonical-json" } }),
];

const live = [
  define({ moduleId: "live", productName: "LiveForum", id: "create-session", title: "Create governed live session", description: "Create a session with purpose, schedule, visibility, and an explicit recording mode.", operation: "mutation", recordType: "live-session", required: ["key", "title", "purpose", "startsAt", "endsAt", "visibility", "recordingMode"], properties: { key: text("Stable session key.", 80), title: text("Session title.", 240), purpose: text("Session purpose.", 2_000), startsAt: dateTime("UTC scheduled start."), endsAt: dateTime("UTC scheduled end."), visibility: enumString("Session visibility.", ["private", "workspace", "invited-public"]), recordingMode: enumString("Recording mode.", ["disabled", "consent-required"]) }, example: { key: "customer-briefing", title: "Customer briefing", purpose: "Product education", startsAt: "2026-09-01T14:00:00.000Z", endsAt: "2026-09-01T15:00:00.000Z", visibility: "invited-public", recordingMode: "consent-required" } }),
  define({ moduleId: "live", productName: "LiveForum", id: "issue-presenter-grant", title: "Issue approved presenter grant", description: "Issue a short-lived least-privileged presenter grant to one exact workspace admin after attributed access approval.", operation: "mutation", recordType: "presenter-grant", externalEffect: "access", required: ["sessionId", "presenterRef", "capabilities", "expiresAt", "accessDecisionReceiptId"], properties: { sessionId: uuid("Live session ID."), presenterRef: text("Exact workspace admin user ID receiving the grant.", 200), capabilities: array("Presenter capabilities.", enumString("Capability.", ["broadcast", "moderate", "prompt", "end"]), 10, 1), expiresAt: dateTime("UTC grant expiry."), accessDecisionReceiptId: text("Immutable access decision receipt.", 240) }, example: { sessionId: sample.record, presenterRef: sample.actor, capabilities: ["broadcast", "prompt", "end"], expiresAt: "2026-09-01T16:00:00.000Z", accessDecisionReceiptId: "presenter-access-42" } }),
  define({ moduleId: "live", productName: "LiveForum", id: "issue-attendee-access", title: "Issue approved attendee access", description: "Issue a short-lived attendee access record to one exact authenticated workspace identity after an explicit access decision.", operation: "mutation", recordType: "attendee-access", externalEffect: "access", required: ["sessionId", "attendeeRef", "accessKind", "expiresAt", "accessDecisionReceiptId"], properties: { sessionId: uuid("Live session ID."), attendeeRef: text("Exact authenticated workspace user ID receiving access.", 200), accessKind: enumString("Attendee capability set.", ["view", "view-and-chat", "view-chat-and-respond"]), expiresAt: dateTime("UTC access expiry."), accessDecisionReceiptId: text("Immutable access decision receipt.", 240) }, example: { sessionId: sample.record, attendeeRef: sample.actor, accessKind: "view-chat-and-respond", expiresAt: "2026-09-01T16:00:00.000Z", accessDecisionReceiptId: "attendee-access-42" } }),
  define({ moduleId: "live", productName: "LiveForum", id: "record-media-consent", title: "Record participant media consent", description: "Record only the authenticated participant's exact granted, declined, or revoked scopes from an immutable subject interaction receipt.", operation: "mutation", recordType: "media-consent-receipt", externalEffect: "consent", requiresApproval: false, supportsDryRun: false, required: ["sessionId", "participantRef", "decision", "scopes", "policyVersion", "capturedAt", "subjectReceiptId"], properties: { sessionId: uuid("Live session ID."), participantRef: text("Exact authenticated workspace user ID giving this decision.", 200), decision: enumString("Participant decision.", ["granted", "declined", "revoked"]), scopes: array("Exact media scopes.", enumString("Consent scope.", ["record-audio", "record-video", "publish-replay"]), 10, 1), policyVersion: text("Exact consent policy version.", 120), capturedAt: dateTime("Subject interaction clock."), subjectReceiptId: text("Immutable subject interaction receipt.", 240) }, example: { sessionId: sample.record, participantRef: sample.actor, decision: "granted", scopes: ["record-audio", "publish-replay"], policyVersion: "media-v1", capturedAt: "2026-09-01T13:50:00.000Z", subjectReceiptId: "media-consent-42" } }),
  define({ moduleId: "live", productName: "LiveForum", id: "start-broadcast", title: "Start approved broadcast", description: "Start a session only with a valid presenter grant and exact consent-ledger snapshot hash.", operation: "mutation", recordType: "broadcast-receipt", externalEffect: "broadcast", required: ["sessionId", "expectedVersion", "presenterGrantId", "startedAt", "consentSnapshotHash"], properties: { sessionId: uuid("Live session ID."), expectedVersion: integer("Current session version.", 1), presenterGrantId: uuid("Presenter grant ID."), startedAt: dateTime("UTC broadcast start."), consentSnapshotHash: sha256("Hash of the exact current session consent receipt set.") }, example: { sessionId: sample.record, expectedVersion: 1, presenterGrantId: sample.evidence, startedAt: "2026-09-01T14:00:00.000Z", consentSnapshotHash: "f".repeat(64) } }),
  define({ moduleId: "live", productName: "LiveForum", id: "update-broadcast", title: "Update approved broadcast state", description: "Apply a bounded stage-mode or agenda update through a valid presenter grant and optimistic lock.", operation: "mutation", recordType: "broadcast-update", externalEffect: "broadcast", required: ["sessionId", "expectedVersion", "presenterGrantId", "stageMode", "agendaNote"], properties: { sessionId: uuid("Live session ID."), expectedVersion: integer("Current session version.", 1), presenterGrantId: uuid("Presenter grant ID."), stageMode: enumString("Stage layout mode.", ["speaker", "panel", "presentation", "break"]), agendaNote: text("Human-authored agenda note.", 2_000) }, example: { sessionId: sample.record, expectedVersion: 2, presenterGrantId: sample.evidence, stageMode: "panel", agendaNote: "Open customer questions" } }),
  define({ moduleId: "live", productName: "LiveForum", id: "send-chat", title: "Send attributed live chat", description: "Append a message only after validating an active access receipt with chat capability.", operation: "mutation", recordType: "live-chat-message", required: ["sessionId", "attendeeAccessId", "body", "sentAt"], properties: { sessionId: uuid("Live session ID."), attendeeAccessId: uuid("Attendee access ID."), body: text("Chat body.", 5_000), sentAt: dateTime("Client submission clock.") }, example: { sessionId: sample.record, attendeeAccessId: sample.evidence, body: "Could you clarify the launch date?", sentAt: "2026-09-01T14:15:00.000Z" } }),
  define({ moduleId: "live", productName: "LiveForum", id: "moderate-chat", title: "Record human chat moderation", description: "Hide or restore one message only after an attributed human moderation decision and valid moderator grant.", operation: "mutation", recordType: "chat-moderation-receipt", destructive: true, externalEffect: "moderation", required: ["messageId", "expectedVersion", "moderatorGrantId", "decision", "reason", "moderationReceiptId"], properties: { messageId: uuid("Chat message ID."), expectedVersion: integer("Current message version.", 1), moderatorGrantId: uuid("Presenter grant with moderation capability."), decision: enumString("Human moderation decision.", ["hide", "restore"]), reason: text("Decision reason grounded in policy.", 2_000), moderationReceiptId: text("Immutable moderation UI receipt.", 240) }, example: { messageId: sample.record, expectedVersion: 1, moderatorGrantId: sample.evidence, decision: "hide", reason: "Contains a credential", moderationReceiptId: "moderation-42" } }),
  define({ moduleId: "live", productName: "LiveForum", id: "open-prompt", title: "Open presenter prompt", description: "Open a bounded poll or question after validating a presenter grant with prompt capability.", operation: "mutation", recordType: "live-prompt", required: ["sessionId", "presenterGrantId", "question", "responseType", "closesAt"], properties: { sessionId: uuid("Live session ID."), presenterGrantId: uuid("Presenter grant ID."), question: text("Prompt question.", 2_000), responseType: enumString("Response type.", ["text", "single-choice", "rating"]), options: stringArray("Options for a single-choice prompt.", 50), closesAt: dateTime("UTC prompt close.") }, example: { sessionId: sample.record, presenterGrantId: sample.evidence, question: "Which topic should we cover next?", responseType: "single-choice", options: ["Security", "Billing"], closesAt: "2026-09-01T14:30:00.000Z" } }),
  define({ moduleId: "live", productName: "LiveForum", id: "submit-response", title: "Submit attributed prompt response", description: "Append one response after validating the attendee access receipt and prompt close clock.", operation: "mutation", recordType: "live-prompt-response", required: ["promptId", "attendeeAccessId", "response", "submittedAt"], properties: { promptId: uuid("Live prompt ID."), attendeeAccessId: uuid("Attendee access ID."), response: text("Response value.", 5_000), submittedAt: dateTime("UTC submission clock.") }, example: { promptId: sample.record, attendeeAccessId: sample.evidence, response: "Security", submittedAt: "2026-09-01T14:20:00.000Z" } }),
  define({ moduleId: "live", productName: "LiveForum", id: "end-broadcast", title: "End approved broadcast", description: "End a live session through a valid presenter grant and persist the exact end receipt.", operation: "mutation", recordType: "broadcast-receipt", externalEffect: "broadcast", required: ["sessionId", "expectedVersion", "presenterGrantId", "endedAt"], properties: { sessionId: uuid("Live session ID."), expectedVersion: integer("Current session version.", 1), presenterGrantId: uuid("Presenter grant ID."), endedAt: dateTime("UTC broadcast end.") }, example: { sessionId: sample.record, expectedVersion: 3, presenterGrantId: sample.evidence, endedAt: "2026-09-01T15:00:00.000Z" } }),
  define({ moduleId: "live", productName: "LiveForum", id: "build-replay", title: "Queue replay highlight proposal", description: "Queue cited chapters and highlight suggestions; it cannot edit media, publish a replay, or override consent.", operation: "ai", recordType: "ai-proposal-request", required: ["sessionId", "goal", "evidenceIds"], properties: { sessionId: uuid("Live session ID."), goal: text("Replay objective.", 2_000), evidenceIds, modelId }, example: { sessionId: sample.record, goal: "Propose consent-compatible chapters and factual highlights.", evidenceIds: [sample.evidence] } }),
];

export const additiveWaveTwoActions: readonly AdditiveWaveTwoActionDefinition[] = [...events, ...people, ...metering, ...assurance, ...live];

export const additiveWaveTwoActionsByModule = new Map<AdditiveWaveTwoModuleId, readonly AdditiveWaveTwoActionDefinition[]>(
  additiveWaveTwoModules.map((module) => [module.id, additiveWaveTwoActions.filter((action) => action.moduleId === module.id)]),
);

export const additiveWaveTwoModuleById = new Map(additiveWaveTwoModules.map((module) => [module.id, module]));

export function additiveWaveTwoAction(moduleId: string, actionId: string) {
  return additiveWaveTwoActions.find((action) => action.moduleId === moduleId && action.id === actionId);
}

export function isAdditiveWaveTwoModule(moduleId: string): moduleId is AdditiveWaveTwoModuleId {
  return additiveWaveTwoModuleById.has(moduleId as AdditiveWaveTwoModuleId);
}

const planRank: Record<AdditiveWaveTwoPlanId, number> = { none: 0, starter: 1, scale: 2, fleet: 3 };
export function additiveWaveTwoPlanAllows(plan: AdditiveWaveTwoPlanId, moduleId: AdditiveWaveTwoModuleId) {
  const module = additiveWaveTwoModuleById.get(moduleId);
  return Boolean(module && planRank[plan] >= planRank[module.minPlan]);
}
