export type PremiumPlanId = "none" | "starter" | "scale" | "fleet";
export type PremiumModuleId = "projects" | "drive" | "channels" | "operations" | "assistant";
export type PremiumActionOperation = "read" | "mutation" | "ai";
export type PremiumActionRisk = "low" | "medium" | "high" | "critical";
export type PremiumExternalEffect = "none" | "message" | "file" | "accounting" | "model";

export interface PremiumResourceProfile {
  class: "high" | "accelerated";
  minimumCpuMillicores: number;
  minimumMemoryMiB: number;
  includedStorageGb: number;
  recommendedWorkerConcurrency: number;
  notes: string;
}

export interface PremiumModuleDefinition {
  id: PremiumModuleId;
  name: string;
  category: string;
  originalProductThesis: string;
  minPlan: Extract<PremiumPlanId, "scale" | "fleet">;
  minimumMonthlyPlanUsd: 50 | 200;
  resource: PremiumResourceProfile;
  aiNativeQualities: readonly string[];
}

export interface PremiumJsonSchema {
  type: "object";
  required: readonly string[];
  properties: Readonly<Record<string, Readonly<Record<string, unknown>>>>;
  additionalProperties: false;
}

export interface PremiumActionDefinition {
  id: string;
  moduleId: PremiumModuleId;
  title: string;
  description: string;
  operation: PremiumActionOperation;
  requiredScope: "read" | "write" | "ai";
  risk: PremiumActionRisk;
  destructive: boolean;
  externalEffect: PremiumExternalEffect;
  requiresApproval: boolean;
  supportsDryRun: boolean;
  idempotent: boolean;
  inputSchema: PremiumJsonSchema;
  mcpToolName: string;
  cliExample: string;
}

export const premiumBusinessModules = [
  {
    id: "projects",
    name: "Northstar Planning",
    category: "Outcome planning",
    originalProductThesis: "Connect issues, dependencies, capacity, decisions, and cited planning assistance in one auditable outcome graph.",
    minPlan: "scale",
    minimumMonthlyPlanUsd: 50,
    resource: { class: "high", minimumCpuMillicores: 500, minimumMemoryMiB: 768, includedStorageGb: 4, recommendedWorkerConcurrency: 2, notes: "Optimized for dependency graphs, cycle snapshots, and bounded planning jobs." },
    aiNativeQualities: ["Evidence-linked plan proposals", "Human-approved cycle commitments", "No autonomous issue transitions"],
  },
  {
    id: "drive",
    name: "Harbor Vault",
    category: "Private files and workspace",
    originalProductThesis: "Treat every file, version, share, retention decision, and cited document analysis as a verifiable private record.",
    minPlan: "scale",
    minimumMonthlyPlanUsd: 50,
    resource: { class: "high", minimumCpuMillicores: 750, minimumMemoryMiB: 1_024, includedStorageGb: 50, recommendedWorkerConcurrency: 2, notes: "Object bytes stay outside records; metadata, checksums, versions, and policy receipts remain tenant-scoped." },
    aiNativeQualities: ["Checksum-pinned evidence", "Citation-only document understanding", "Approval-gated shares and deletion"],
  },
  {
    id: "channels",
    name: "Threadline",
    category: "Topic-first team communication",
    originalProductThesis: "Make decisions and open questions first-class topic records while keeping every outbound message previewable and reviewable.",
    minPlan: "scale",
    minimumMonthlyPlanUsd: 50,
    resource: { class: "high", minimumCpuMillicores: 600, minimumMemoryMiB: 1_024, includedStorageGb: 8, recommendedWorkerConcurrency: 4, notes: "Designed for topic indexes, message receipts, and bounded asynchronous summaries." },
    aiNativeQualities: ["Evidence-cited topic summaries", "Preview-hash message approvals", "No model-authored message is sent silently"],
  },
  {
    id: "operations",
    name: "Ledgerline Operations",
    category: "Business operations and accounting",
    originalProductThesis: "Unify orders, invoices, inventory facts, and balanced immutable journals without allowing AI to post money-moving facts.",
    minPlan: "fleet",
    minimumMonthlyPlanUsd: 200,
    resource: { class: "high", minimumCpuMillicores: 1_000, minimumMemoryMiB: 2_048, includedStorageGb: 25, recommendedWorkerConcurrency: 4, notes: "Uses integer minor units, immutable posting snapshots, and explicit accounting approvals." },
    aiNativeQualities: ["Cited variance explanations", "Deterministic double-entry validation", "AI cannot post journals or payments"],
  },
  {
    id: "assistant",
    name: "Evident AI Workbench",
    category: "Grounded model and agent workbench",
    originalProductThesis: "Version prompts, bind evidence, authorize model runs, review cited claims, and constrain agents to an immutable action allowlist.",
    minPlan: "fleet",
    minimumMonthlyPlanUsd: 200,
    resource: { class: "accelerated", minimumCpuMillicores: 2_000, minimumMemoryMiB: 4_096, includedStorageGb: 30, recommendedWorkerConcurrency: 2, notes: "Local or customer-selected models can be attached later; the core stores no provider secret and fabricates no result." },
    aiNativeQualities: ["Prompt and model provenance", "Claim-level evidence requirements", "Explicit review and action approval"],
  },
] as const satisfies readonly PremiumModuleDefinition[];

const string = (description: string, options: Record<string, unknown> = {}) => ({ type: "string", description, ...options });
const integer = (description: string, options: Record<string, unknown> = {}) => ({ type: "integer", description, ...options });
const boolean = (description: string) => ({ type: "boolean", description });
const array = (description: string, items: Record<string, unknown> = {}) => ({ type: "array", description, items, maxItems: 200 });
const object = (description: string) => ({ type: "object", description });
const id = (description: string) => string(description, { format: "uuid" });
const key = string("A retry-safe key unique to this logical mutation.", { pattern: "^[A-Za-z0-9._:-]{16,200}$" });
const approval = object("Explicit single-use human approval: {approved:true, approvedBy, approvedAt, decisionId, reason}. decisionId must uniquely identify this exact reviewed decision.");
const dryRun = boolean("When true, validate and return a receipt without applying the mutation or external effect.");
const evidenceIds = array("Tenant-owned record IDs that ground the requested output.", { type: "string", format: "uuid" });
const promptVersion = string("Immutable prompt policy version used for this request.", { pattern: "^[A-Za-z0-9._:-]{3,120}$" });
const modelId = string("Optional exact assertion of the host-configured model policy. Omit it to use the trusted host policy; it never selects a caller-controlled model or carries a secret.", { minLength: 1, maxLength: 200 });

function schema(required: readonly string[], properties: PremiumJsonSchema["properties"]): PremiumJsonSchema {
  return { type: "object", required: required.filter((name) => name !== "approval"), properties, additionalProperties: false };
}

function mutationFields(properties: PremiumJsonSchema["properties"] = {}) {
  return { ...properties, idempotencyKey: key };
}

function gatedFields(properties: PremiumJsonSchema["properties"] = {}) {
  return { ...properties, approval, dryRun, idempotencyKey: key };
}

function action<const M extends PremiumModuleId, const I extends string>(definition: Omit<PremiumActionDefinition, "moduleId" | "id" | "mcpToolName"> & { moduleId: M; id: I }): PremiumActionDefinition & { moduleId: M; id: I } {
  return { ...definition, mcpToolName: `${definition.moduleId}_${definition.id.replaceAll("-", "_")}` };
}

export const premiumBusinessActions = [
  action({ moduleId: "projects", id: "project-create", title: "Create outcome project", description: "Create a project with an immutable outcome statement and stable key.", operation: "mutation", requiredScope: "write", risk: "low", destructive: false, externalEffect: "none", requiresApproval: false, supportsDryRun: false, idempotent: true, inputSchema: schema(["key", "name", "outcome", "idempotencyKey"], mutationFields({ key: string("Stable lowercase project key.", { pattern: "^[a-z][a-z0-9-]{1,39}$" }), name: string("Project name.", { maxLength: 160 }), outcome: string("Measurable intended outcome.", { maxLength: 2000 }) })), cliExample: "supersuite projects project-create --input '{\"key\":\"launch\",\"name\":\"Launch\",\"outcome\":\"Ship safely\",\"idempotencyKey\":\"project-launch-0001\"}'" }),
  action({ moduleId: "projects", id: "issue-create", title: "Create scoped issue", description: "Create a pointed issue within one tenant-owned project.", operation: "mutation", requiredScope: "write", risk: "low", destructive: false, externalEffect: "none", requiresApproval: false, supportsDryRun: false, idempotent: true, inputSchema: schema(["projectId", "title", "priority", "points", "idempotencyKey"], mutationFields({ projectId: id("Owning project ID."), title: string("Issue title.", { maxLength: 240 }), priority: string("Priority.", { enum: ["urgent", "high", "normal", "low"] }), points: integer("Whole capacity points.", { minimum: 1, maximum: 100 }) })), cliExample: "supersuite projects issue-create --input @issue.json" }),
  action({ moduleId: "projects", id: "dependency-link", title: "Link issue dependency", description: "Add an acyclic dependency between issues in the same project.", operation: "mutation", requiredScope: "write", risk: "medium", destructive: false, externalEffect: "none", requiresApproval: false, supportsDryRun: false, idempotent: true, inputSchema: schema(["issueId", "dependsOnIssueId", "expectedVersion", "idempotencyKey"], mutationFields({ issueId: id("Blocked issue ID."), dependsOnIssueId: id("Required issue ID."), expectedVersion: integer("Current issue version.", { minimum: 1 }) })), cliExample: "supersuite projects dependency-link --input @dependency.json" }),
  action({ moduleId: "projects", id: "issue-transition", title: "Transition issue", description: "Apply a valid optimistic-lock state transition without model autonomy.", operation: "mutation", requiredScope: "write", risk: "medium", destructive: false, externalEffect: "none", requiresApproval: false, supportsDryRun: false, idempotent: true, inputSchema: schema(["issueId", "toState", "expectedVersion", "reason", "idempotencyKey"], mutationFields({ issueId: id("Issue ID."), toState: string("Target state.", { enum: ["ready", "active", "blocked", "done"] }), expectedVersion: integer("Current issue version.", { minimum: 1 }), reason: string("Auditable reason.", { maxLength: 1000 }) })), cliExample: "supersuite projects issue-transition --input @transition.json" }),
  action({ moduleId: "projects", id: "cycle-draft", title: "Draft capacity-safe cycle", description: "Freeze a bounded issue and capacity snapshot before commitment.", operation: "mutation", requiredScope: "write", risk: "medium", destructive: false, externalEffect: "none", requiresApproval: false, supportsDryRun: false, idempotent: true, inputSchema: schema(["projectId", "title", "capacityPoints", "issueIds", "idempotencyKey"], mutationFields({ projectId: id("Project ID."), title: string("Cycle title.", { maxLength: 160 }), capacityPoints: integer("Available capacity points.", { minimum: 1, maximum: 10000 }), issueIds: array("Unique issue IDs selected for the cycle.", { type: "string", format: "uuid" }) })), cliExample: "supersuite projects cycle-draft --input @cycle.json" }),
  action({ moduleId: "projects", id: "cycle-commit", title: "Commit reviewed cycle", description: "Commit the exact capacity snapshot only after explicit approval.", operation: "mutation", requiredScope: "write", risk: "high", destructive: false, externalEffect: "none", requiresApproval: true, supportsDryRun: true, idempotent: true, inputSchema: schema(["cycleId", "contentHash", "approval", "dryRun", "idempotencyKey"], gatedFields({ cycleId: id("Draft cycle ID."), contentHash: string("Exact cycle SHA-256 hash.", { pattern: "^[a-f0-9]{64}$" }) })), cliExample: "supersuite projects cycle-commit --input @approved-cycle.json" }),
  action({ moduleId: "projects", id: "plan-propose", title: "Queue cited plan proposal", description: "Queue a proposal-only planning run pinned to evidence and prompt versions under the host-configured model policy; modelId is only an optional exact assertion.", operation: "ai", requiredScope: "ai", risk: "high", destructive: false, externalEffect: "model", requiresApproval: true, supportsDryRun: true, idempotent: true, inputSchema: schema(["projectId", "objective", "evidenceIds", "promptVersion", "approval", "dryRun", "idempotencyKey"], gatedFields({ projectId: id("Project ID."), objective: string("Planning objective.", { maxLength: 4000 }), evidenceIds, promptVersion, modelId })), cliExample: "supersuite projects plan-propose --input @approved-plan-run.json" }),
  action({ moduleId: "projects", id: "health-explain", title: "Queue cited project health explanation", description: "Queue a non-mutating explanation with explicit source evidence and review under the host-configured model policy; modelId is only an optional exact assertion.", operation: "ai", requiredScope: "ai", risk: "medium", destructive: false, externalEffect: "model", requiresApproval: true, supportsDryRun: true, idempotent: true, inputSchema: schema(["projectId", "question", "evidenceIds", "promptVersion", "approval", "dryRun", "idempotencyKey"], gatedFields({ projectId: id("Project ID."), question: string("Question to answer from evidence.", { maxLength: 4000 }), evidenceIds, promptVersion, modelId })), cliExample: "supersuite projects health-explain --input @approved-health-run.json" }),

  action({ moduleId: "drive", id: "vault-create", title: "Create private vault", description: "Create an isolated metadata boundary for versioned files.", operation: "mutation", requiredScope: "write", risk: "low", destructive: false, externalEffect: "none", requiresApproval: false, supportsDryRun: false, idempotent: true, inputSchema: schema(["name", "classification", "idempotencyKey"], mutationFields({ name: string("Vault name.", { maxLength: 160 }), classification: string("Data classification.", { enum: ["internal", "confidential", "restricted"] }) })), cliExample: "supersuite drive vault-create --input @vault.json" }),
  action({ moduleId: "drive", id: "file-register", title: "Register checked file", description: "Register object metadata only after checksum, size, and human authorization checks.", operation: "mutation", requiredScope: "write", risk: "high", destructive: false, externalEffect: "file", requiresApproval: true, supportsDryRun: true, idempotent: true, inputSchema: schema(["vaultId", "name", "objectKey", "contentType", "sizeBytes", "checksum", "approval", "dryRun", "idempotencyKey"], gatedFields({ vaultId: id("Vault ID."), name: string("Display filename.", { maxLength: 240 }), objectKey: string("Opaque object storage key; never a credential.", { maxLength: 1000 }), contentType: string("Media type.", { maxLength: 200 }), sizeBytes: integer("Object size in bytes.", { minimum: 1, maximum: 5368709120 }), checksum: string("Object SHA-256 checksum.", { pattern: "^[a-f0-9]{64}$" }) })), cliExample: "supersuite drive file-register --input @approved-file.json" }),
  action({ moduleId: "drive", id: "file-version-add", title: "Add immutable file version", description: "Add a checksum-addressed file version with optimistic locking.", operation: "mutation", requiredScope: "write", risk: "high", destructive: false, externalEffect: "file", requiresApproval: true, supportsDryRun: true, idempotent: true, inputSchema: schema(["fileId", "objectKey", "sizeBytes", "checksum", "expectedVersion", "approval", "dryRun", "idempotencyKey"], gatedFields({ fileId: id("File ID."), objectKey: string("Opaque object key.", { maxLength: 1000 }), sizeBytes: integer("Object size in bytes.", { minimum: 1, maximum: 5368709120 }), checksum: string("SHA-256 checksum.", { pattern: "^[a-f0-9]{64}$" }), expectedVersion: integer("Current file version.", { minimum: 1 }) })), cliExample: "supersuite drive file-version-add --input @approved-version.json" }),
  action({ moduleId: "drive", id: "share-preview", title: "Preview pinned file share", description: "Create a deterministic share plan without publishing a token.", operation: "read", requiredScope: "read", risk: "medium", destructive: false, externalEffect: "none", requiresApproval: false, supportsDryRun: false, idempotent: false, inputSchema: schema(["fileId", "expiresAt", "permission"], { fileId: id("File ID."), expiresAt: string("Expiry date-time.", { format: "date-time" }), permission: string("Share permission.", { enum: ["view", "download"] }) }), cliExample: "supersuite drive share-preview --input @share-preview.json" }),
  action({ moduleId: "drive", id: "share-create", title: "Create approved pinned share", description: "Publish an expiring checksum-pinned share after exact preview approval.", operation: "mutation", requiredScope: "write", risk: "critical", destructive: false, externalEffect: "file", requiresApproval: true, supportsDryRun: true, idempotent: true, inputSchema: schema(["fileId", "expiresAt", "permission", "previewHash", "approval", "dryRun", "idempotencyKey"], gatedFields({ fileId: id("File ID."), expiresAt: string("Expiry date-time.", { format: "date-time" }), permission: string("Share permission.", { enum: ["view", "download"] }), previewHash: string("Exact preview SHA-256 hash.", { pattern: "^[a-f0-9]{64}$" }) })), cliExample: "supersuite drive share-create --input @approved-share.json" }),
  action({ moduleId: "drive", id: "retention-set", title: "Set file retention policy", description: "Apply retention or legal hold controls with version and approval evidence.", operation: "mutation", requiredScope: "write", risk: "high", destructive: false, externalEffect: "file", requiresApproval: true, supportsDryRun: true, idempotent: true, inputSchema: schema(["fileId", "retainUntil", "legalHold", "expectedVersion", "approval", "dryRun", "idempotencyKey"], gatedFields({ fileId: id("File ID."), retainUntil: string("Retention date-time.", { format: "date-time" }), legalHold: boolean("Whether deletion must be blocked until an explicit later policy change."), expectedVersion: integer("Current file version.", { minimum: 1 }) })), cliExample: "supersuite drive retention-set --input @approved-retention.json" }),
  action({ moduleId: "drive", id: "file-delete", title: "Soft-delete eligible file", description: "Soft-delete only when no legal hold or active retention window exists.", operation: "mutation", requiredScope: "write", risk: "critical", destructive: true, externalEffect: "file", requiresApproval: true, supportsDryRun: true, idempotent: true, inputSchema: schema(["fileId", "expectedVersion", "reason", "approval", "dryRun", "idempotencyKey"], gatedFields({ fileId: id("File ID."), expectedVersion: integer("Current file version.", { minimum: 1 }), reason: string("Deletion reason.", { maxLength: 1000 }) })), cliExample: "supersuite drive file-delete --input @approved-delete.json" }),
  action({ moduleId: "drive", id: "document-understand", title: "Queue cited document understanding", description: "Queue analysis under the host-configured model policy against an exact checksum without placing object keys or secrets in context; modelId is only an optional exact assertion.", operation: "ai", requiredScope: "ai", risk: "high", destructive: false, externalEffect: "model", requiresApproval: true, supportsDryRun: true, idempotent: true, inputSchema: schema(["fileId", "question", "evidenceIds", "promptVersion", "approval", "dryRun", "idempotencyKey"], gatedFields({ fileId: id("File ID."), question: string("Question about the file.", { maxLength: 4000 }), evidenceIds, promptVersion, modelId })), cliExample: "supersuite drive document-understand --input @approved-document-run.json" }),

  action({ moduleId: "channels", id: "stream-create", title: "Create communication stream", description: "Create a purpose-bound stream for topic-first communication.", operation: "mutation", requiredScope: "write", risk: "low", destructive: false, externalEffect: "none", requiresApproval: false, supportsDryRun: false, idempotent: true, inputSchema: schema(["key", "name", "purpose", "idempotencyKey"], mutationFields({ key: string("Stable stream key.", { pattern: "^[a-z][a-z0-9-]{1,39}$" }), name: string("Stream name.", { maxLength: 160 }), purpose: string("Stream purpose.", { maxLength: 2000 }) })), cliExample: "supersuite channels stream-create --input @stream.json" }),
  action({ moduleId: "channels", id: "topic-create", title: "Create decision topic", description: "Create a bounded topic with an explicit question or intended decision.", operation: "mutation", requiredScope: "write", risk: "low", destructive: false, externalEffect: "none", requiresApproval: false, supportsDryRun: false, idempotent: true, inputSchema: schema(["streamId", "title", "intent", "idempotencyKey"], mutationFields({ streamId: id("Stream ID."), title: string("Topic title.", { maxLength: 240 }), intent: string("Question, decision, or coordination intent.", { maxLength: 2000 }) })), cliExample: "supersuite channels topic-create --input @topic.json" }),
  action({ moduleId: "channels", id: "message-preview", title: "Preview outbound message", description: "Validate and hash the exact topic message without sending or storing it.", operation: "read", requiredScope: "read", risk: "medium", destructive: false, externalEffect: "none", requiresApproval: false, supportsDryRun: false, idempotent: false, inputSchema: schema(["topicId", "body"], { topicId: id("Topic ID."), body: string("Plain-text message body.", { maxLength: 12000 }) }), cliExample: "supersuite channels message-preview --input @message.json" }),
  action({ moduleId: "channels", id: "message-post", title: "Post approved topic message", description: "Post only the exact previewed message after explicit approval.", operation: "mutation", requiredScope: "write", risk: "high", destructive: false, externalEffect: "message", requiresApproval: true, supportsDryRun: true, idempotent: true, inputSchema: schema(["topicId", "body", "previewHash", "approval", "dryRun", "idempotencyKey"], gatedFields({ topicId: id("Topic ID."), body: string("Plain-text message body.", { maxLength: 12000 }), previewHash: string("Exact preview SHA-256 hash.", { pattern: "^[a-f0-9]{64}$" }) })), cliExample: "supersuite channels message-post --input @approved-message.json" }),
  action({ moduleId: "channels", id: "message-redact", title: "Redact message body", description: "Remove displayed message content while preserving an immutable hash and reason receipt.", operation: "mutation", requiredScope: "write", risk: "critical", destructive: true, externalEffect: "message", requiresApproval: true, supportsDryRun: true, idempotent: true, inputSchema: schema(["messageId", "expectedVersion", "reason", "approval", "dryRun", "idempotencyKey"], gatedFields({ messageId: id("Message ID."), expectedVersion: integer("Current message version.", { minimum: 1 }), reason: string("Redaction reason.", { maxLength: 1000 }) })), cliExample: "supersuite channels message-redact --input @approved-redaction.json" }),
  action({ moduleId: "channels", id: "topic-resolve", title: "Resolve topic", description: "Close a topic with an explicit human-authored decision and optimistic locking.", operation: "mutation", requiredScope: "write", risk: "medium", destructive: false, externalEffect: "none", requiresApproval: false, supportsDryRun: false, idempotent: true, inputSchema: schema(["topicId", "decision", "expectedVersion", "idempotencyKey"], mutationFields({ topicId: id("Topic ID."), decision: string("Final decision or resolution.", { maxLength: 4000 }), expectedVersion: integer("Current topic version.", { minimum: 1 }) })), cliExample: "supersuite channels topic-resolve --input @resolution.json" }),
  action({ moduleId: "channels", id: "topic-summarize", title: "Queue cited topic summary", description: "Queue a proposal-only summary from selected message evidence under the host-configured model policy; modelId is only an optional exact assertion.", operation: "ai", requiredScope: "ai", risk: "high", destructive: false, externalEffect: "model", requiresApproval: true, supportsDryRun: true, idempotent: true, inputSchema: schema(["topicId", "question", "evidenceIds", "promptVersion", "approval", "dryRun", "idempotencyKey"], gatedFields({ topicId: id("Topic ID."), question: string("Summary objective.", { maxLength: 4000 }), evidenceIds, promptVersion, modelId })), cliExample: "supersuite channels topic-summarize --input @approved-topic-run.json" }),
  action({ moduleId: "channels", id: "digest-draft", title: "Queue cited stream digest", description: "Queue a review-required digest from selected topic records under the host-configured model policy; modelId is only an optional exact assertion.", operation: "ai", requiredScope: "ai", risk: "high", destructive: false, externalEffect: "model", requiresApproval: true, supportsDryRun: true, idempotent: true, inputSchema: schema(["streamId", "instruction", "evidenceIds", "promptVersion", "approval", "dryRun", "idempotencyKey"], gatedFields({ streamId: id("Stream ID."), instruction: string("Digest objective.", { maxLength: 4000 }), evidenceIds, promptVersion, modelId })), cliExample: "supersuite channels digest-draft --input @approved-digest-run.json" }),

  action({ moduleId: "operations", id: "party-create", title: "Create business party", description: "Create a customer or supplier without embedding provider credentials.", operation: "mutation", requiredScope: "write", risk: "medium", destructive: false, externalEffect: "none", requiresApproval: false, supportsDryRun: false, idempotent: true, inputSchema: schema(["name", "kind", "currency", "idempotencyKey"], mutationFields({ name: string("Party name.", { maxLength: 240 }), kind: string("Party kind.", { enum: ["customer", "supplier"] }), currency: string("ISO 4217 currency.", { pattern: "^[A-Z]{3}$" }) })), cliExample: "supersuite operations party-create --input @party.json" }),
  action({ moduleId: "operations", id: "item-create", title: "Create catalog item", description: "Create a sellable or purchasable item with integer-minor-unit pricing.", operation: "mutation", requiredScope: "write", risk: "medium", destructive: false, externalEffect: "none", requiresApproval: false, supportsDryRun: false, idempotent: true, inputSchema: schema(["sku", "name", "currency", "unitPriceMinor", "idempotencyKey"], mutationFields({ sku: string("Stable SKU.", { pattern: "^[A-Za-z0-9._-]{2,80}$" }), name: string("Item name.", { maxLength: 240 }), currency: string("ISO 4217 currency.", { pattern: "^[A-Z]{3}$" }), unitPriceMinor: integer("Price in integer minor units.", { minimum: 0, maximum: 1000000000000 }) })), cliExample: "supersuite operations item-create --input @item.json" }),
  action({ moduleId: "operations", id: "order-create", title: "Create snapshotted order", description: "Create an order from exact catalog facts using integer quantity and minor units.", operation: "mutation", requiredScope: "write", risk: "high", destructive: false, externalEffect: "none", requiresApproval: false, supportsDryRun: false, idempotent: true, inputSchema: schema(["partyId", "currency", "lines", "idempotencyKey"], mutationFields({ partyId: id("Customer party ID."), currency: string("ISO currency.", { pattern: "^[A-Z]{3}$" }), lines: array("Order lines: {itemId, quantity}.", { type: "object" }) })), cliExample: "supersuite operations order-create --input @order.json" }),
  action({ moduleId: "operations", id: "invoice-draft", title: "Draft immutable invoice", description: "Draft an invoice from an exact order snapshot without issuing or delivering it.", operation: "mutation", requiredScope: "write", risk: "high", destructive: false, externalEffect: "none", requiresApproval: false, supportsDryRun: false, idempotent: true, inputSchema: schema(["orderId", "issueAt", "dueAt", "idempotencyKey"], mutationFields({ orderId: id("Order ID."), issueAt: string("Issue date-time.", { format: "date-time" }), dueAt: string("Due date-time.", { format: "date-time" }) })), cliExample: "supersuite operations invoice-draft --input @invoice.json" }),
  action({ moduleId: "operations", id: "invoice-issue", title: "Issue approved invoice", description: "Open the exact content-addressed invoice for payment without delivering it to an external recipient.", operation: "mutation", requiredScope: "write", risk: "critical", destructive: false, externalEffect: "accounting", requiresApproval: true, supportsDryRun: true, idempotent: true, inputSchema: schema(["invoiceId", "contentHash", "approval", "dryRun", "idempotencyKey"], gatedFields({ invoiceId: id("Draft invoice ID."), contentHash: string("Exact invoice SHA-256 hash.", { pattern: "^[a-f0-9]{64}$" }) })), cliExample: "supersuite operations invoice-issue --input @approved-invoice.json" }),
  action({ moduleId: "operations", id: "journal-preview", title: "Preview balanced journal", description: "Validate double-entry balance and freeze a posting hash without writing a ledger fact.", operation: "read", requiredScope: "read", risk: "high", destructive: false, externalEffect: "none", requiresApproval: false, supportsDryRun: false, idempotent: false, inputSchema: schema(["currency", "period", "memo", "entries"], { currency: string("ISO currency.", { pattern: "^[A-Z]{3}$" }), period: string("Accounting period YYYY-MM.", { pattern: "^\\d{4}-\\d{2}$" }), memo: string("Journal memo.", { maxLength: 1000 }), entries: array("Entries: {account,debitMinor,creditMinor}.", { type: "object" }) }), cliExample: "supersuite operations journal-preview --input @journal.json" }),
  action({ moduleId: "operations", id: "journal-post", title: "Post approved balanced journal", description: "Persist the exact previewed balanced journal as an immutable accounting fact.", operation: "mutation", requiredScope: "write", risk: "critical", destructive: false, externalEffect: "accounting", requiresApproval: true, supportsDryRun: true, idempotent: true, inputSchema: schema(["currency", "period", "memo", "entries", "previewHash", "approval", "dryRun", "idempotencyKey"], gatedFields({ currency: string("ISO currency.", { pattern: "^[A-Z]{3}$" }), period: string("Accounting period YYYY-MM.", { pattern: "^\\d{4}-\\d{2}$" }), memo: string("Journal memo.", { maxLength: 1000 }), entries: array("Entries: {account,debitMinor,creditMinor}.", { type: "object" }), previewHash: string("Exact preview SHA-256 hash.", { pattern: "^[a-f0-9]{64}$" }) })), cliExample: "supersuite operations journal-post --input @approved-journal.json" }),
  action({ moduleId: "operations", id: "payment-record", title: "Record approved payment fact", description: "Append an idempotent payment and recompute invoice balance in integer minor units.", operation: "mutation", requiredScope: "write", risk: "critical", destructive: false, externalEffect: "accounting", requiresApproval: true, supportsDryRun: true, idempotent: true, inputSchema: schema(["invoiceId", "amountMinor", "currency", "reference", "approval", "dryRun", "idempotencyKey"], gatedFields({ invoiceId: id("Invoice ID."), amountMinor: integer("Amount in integer minor units.", { minimum: 1, maximum: 1000000000000 }), currency: string("ISO currency.", { pattern: "^[A-Z]{3}$" }), reference: string("External reference, never a credential.", { maxLength: 240 }) })), cliExample: "supersuite operations payment-record --input @approved-payment.json" }),
  action({ moduleId: "operations", id: "variance-explain", title: "Queue cited variance explanation", description: "Queue a non-posting explanation grounded in selected records under the host-configured model policy; modelId is only an optional exact assertion.", operation: "ai", requiredScope: "ai", risk: "high", destructive: false, externalEffect: "model", requiresApproval: true, supportsDryRun: true, idempotent: true, inputSchema: schema(["question", "evidenceIds", "promptVersion", "approval", "dryRun", "idempotencyKey"], gatedFields({ question: string("Variance question.", { maxLength: 4000 }), evidenceIds, promptVersion, modelId })), cliExample: "supersuite operations variance-explain --input @approved-variance-run.json" }),

  action({ moduleId: "assistant", id: "collection-create", title: "Create evidence collection", description: "Create a scoped collection for prompt and model runs.", operation: "mutation", requiredScope: "write", risk: "low", destructive: false, externalEffect: "none", requiresApproval: false, supportsDryRun: false, idempotent: true, inputSchema: schema(["name", "purpose", "idempotencyKey"], mutationFields({ name: string("Collection name.", { maxLength: 160 }), purpose: string("Allowed evidence purpose.", { maxLength: 2000 }) })), cliExample: "supersuite assistant collection-create --input @collection.json" }),
  action({ moduleId: "assistant", id: "source-attach", title: "Attach checksum evidence", description: "Attach a tenant-owned record to a collection without copying its raw private payload.", operation: "mutation", requiredScope: "write", risk: "medium", destructive: false, externalEffect: "none", requiresApproval: false, supportsDryRun: false, idempotent: true, inputSchema: schema(["collectionId", "recordId", "citationLabel", "contentHash", "idempotencyKey"], mutationFields({ collectionId: id("Collection ID."), recordId: id("Tenant-owned source record ID."), citationLabel: string("Human-readable citation label.", { maxLength: 240 }), contentHash: string("Exact source SHA-256 hash.", { pattern: "^[a-f0-9]{64}$" }) })), cliExample: "supersuite assistant source-attach --input @source.json" }),
  action({ moduleId: "assistant", id: "prompt-version-create", title: "Create immutable prompt version", description: "Freeze system instruction and input/output contracts as content-addressed policy.", operation: "mutation", requiredScope: "write", risk: "high", destructive: false, externalEffect: "none", requiresApproval: false, supportsDryRun: false, idempotent: true, inputSchema: schema(["name", "systemInstruction", "inputContract", "outputContract", "idempotencyKey"], mutationFields({ name: string("Prompt name.", { maxLength: 160 }), systemInstruction: string("System instruction.", { maxLength: 20000 }), inputContract: object("Bounded JSON input contract."), outputContract: object("Bounded JSON output contract requiring evidence.") })), cliExample: "supersuite assistant prompt-version-create --input @prompt.json" }),
  action({ moduleId: "assistant", id: "run-preview", title: "Preview grounded model run", description: "Validate prompt, collection, evidence, host model policy, and review requirements without invoking a model; modelId is only an optional exact assertion.", operation: "read", requiredScope: "read", risk: "high", destructive: false, externalEffect: "none", requiresApproval: false, supportsDryRun: false, idempotent: false, inputSchema: schema(["promptVersionId", "collectionId", "evidenceIds", "goal"], { promptVersionId: id("Prompt version ID."), collectionId: id("Evidence collection ID."), evidenceIds, modelId, goal: string("Run goal.", { maxLength: 4000 }) }), cliExample: "supersuite assistant run-preview --input @run.json" }),
  action({ moduleId: "assistant", id: "run-execute", title: "Authorize grounded model run", description: "Queue an exact previewed run under the host-configured model policy; modelId is only an optional exact assertion and no output is invented by the control plane.", operation: "ai", requiredScope: "ai", risk: "critical", destructive: false, externalEffect: "model", requiresApproval: true, supportsDryRun: true, idempotent: true, inputSchema: schema(["promptVersionId", "collectionId", "evidenceIds", "goal", "previewHash", "approval", "dryRun", "idempotencyKey"], gatedFields({ promptVersionId: id("Prompt version ID."), collectionId: id("Evidence collection ID."), evidenceIds, modelId, goal: string("Run goal.", { maxLength: 4000 }), previewHash: string("Exact preview SHA-256 hash.", { pattern: "^[a-f0-9]{64}$" }) })), cliExample: "supersuite assistant run-execute --input @approved-run.json" }),
  action({ moduleId: "assistant", id: "result-record", title: "Record reviewed cited result", description: "Store claim-level cited output only with model, prompt, confidence, and human review provenance.", operation: "mutation", requiredScope: "write", risk: "critical", destructive: false, externalEffect: "model", requiresApproval: true, supportsDryRun: true, idempotent: true, inputSchema: schema(["runId", "output", "confidence", "evidenceIds", "review", "approval", "dryRun", "idempotencyKey"], gatedFields({ runId: id("Queued run ID."), output: object("{summary, claims:[{text,evidenceIds}]} with no unsupported claim."), confidence: integer("Whole confidence percentage.", { minimum: 0, maximum: 100 }), evidenceIds, review: object("{status:'approved'|'rejected', reviewedBy, reviewedAt, notes}.") })), cliExample: "supersuite assistant result-record --input @reviewed-result.json" }),
  action({ moduleId: "assistant", id: "agent-draft", title: "Draft constrained agent", description: "Create an inert agent version with an immutable prompt and action allowlist.", operation: "mutation", requiredScope: "write", risk: "high", destructive: false, externalEffect: "none", requiresApproval: false, supportsDryRun: false, idempotent: true, inputSchema: schema(["name", "purpose", "promptVersionId", "allowedActions", "maximumSteps", "idempotencyKey"], mutationFields({ name: string("Agent name.", { maxLength: 160 }), purpose: string("Narrow agent purpose.", { maxLength: 2000 }), promptVersionId: id("Prompt version ID."), allowedActions: array("Exact premium MCP action names the agent may propose.", { type: "string" }), maximumSteps: integer("Maximum proposed steps.", { minimum: 1, maximum: 50 }) })), cliExample: "supersuite assistant agent-draft --input @agent.json" }),
  action({ moduleId: "assistant", id: "agent-approve", title: "Approve exact agent version", description: "Approve only the exact inert agent content hash after explicit human review.", operation: "mutation", requiredScope: "write", risk: "critical", destructive: false, externalEffect: "model", requiresApproval: true, supportsDryRun: true, idempotent: true, inputSchema: schema(["agentId", "contentHash", "approval", "dryRun", "idempotencyKey"], gatedFields({ agentId: id("Agent ID."), contentHash: string("Exact agent SHA-256 hash.", { pattern: "^[a-f0-9]{64}$" }) })), cliExample: "supersuite assistant agent-approve --input @approved-agent.json" }),
  action({ moduleId: "assistant", id: "agent-execute", title: "Authorize constrained agent run", description: "Queue an approved agent under the host-configured model policy; modelId is only an optional exact assertion, and the agent cannot execute mutations autonomously.", operation: "ai", requiredScope: "ai", risk: "critical", destructive: false, externalEffect: "model", requiresApproval: true, supportsDryRun: true, idempotent: true, inputSchema: schema(["agentId", "goal", "evidenceIds", "approval", "dryRun", "idempotencyKey"], gatedFields({ agentId: id("Approved agent ID."), goal: string("Run goal.", { maxLength: 4000 }), evidenceIds, modelId })), cliExample: "supersuite assistant agent-execute --input @approved-agent-run.json" }),
] as const;

export type PremiumBusinessAction = typeof premiumBusinessActions[number];
export type PremiumActionIdFor<M extends PremiumModuleId> = Extract<PremiumBusinessAction, { moduleId: M }>["id"];

export const premiumBusinessModuleById = new Map(premiumBusinessModules.map((module) => [module.id, module]));
export const premiumBusinessActionsByModule = new Map<PremiumModuleId, readonly PremiumBusinessAction[]>(premiumBusinessModules.map((module) => [module.id, premiumBusinessActions.filter((candidate) => candidate.moduleId === module.id)]));

export function premiumBusinessAction<M extends PremiumModuleId>(moduleId: M, actionId: PremiumActionIdFor<M>) {
  return premiumBusinessActions.find((candidate) => candidate.moduleId === moduleId && candidate.id === actionId) as Extract<PremiumBusinessAction, { moduleId: M }> | undefined;
}

const planRank: Record<PremiumPlanId, number> = { none: 0, starter: 1, scale: 2, fleet: 3 };
export function premiumPlanAllows(plan: PremiumPlanId, module: PremiumModuleDefinition) { return planRank[plan] >= planRank[module.minPlan]; }
